export const OPENING_KNOWLEDGE_SOURCE = "chess-coach-opening-knowledge-v1";

const generalKnowledge = Object.freeze({
  overview: "In der Eröffnung geht es vor allem um Zentrum, Entwicklung, Königssicherheit und das Zusammenspiel der Figuren.",
  pawnStructures: [
    "Bauernzüge bestimmen Raum, offene Linien und die späteren Hebel. Unnötige Bauernzüge lassen sich nicht zurücknehmen.",
    "Eine Bauernkette sollte an ihrer Basis und mit passenden Bauernhebeln angegriffen werden.",
  ],
  development: [
    "Leichtfiguren gehören auf aktive Felder, von denen sie das Zentrum beeinflussen und sich nicht gegenseitig behindern.",
    "Die Rochade verbindet meist Königssicherheit mit der Aktivierung eines Turms.",
  ],
  whitePlans: [
    "Den Anzugsvorteil für zügige Entwicklung und dauerhaften Einfluss im Zentrum nutzen.",
    "Erst alle Figuren ins Spiel bringen und dann den passenden Bauernhebel oder Angriff vorbereiten.",
  ],
  blackPlans: [
    "Das weiße Zentrum rechtzeitig bestreiten und ohne unnötige Schwächen ausgleichen.",
    "Die Entwicklung abschließen, bevor ein Flügelangriff oder Materialgewinn verfolgt wird.",
  ],
  commonMistakes: [
    "Dieselbe Figur ohne konkreten Grund mehrfach ziehen.",
    "Die Dame früh Angriffen aussetzen und dadurch Entwicklungstempi verlieren.",
    "Einen Flügelangriff beginnen, während König und übrige Figuren noch unentwickelt sind.",
  ],
  explanations: [
    "Ein guter Entwicklungszug erfüllt möglichst mehrere Aufgaben: Er aktiviert eine Figur, beeinflusst das Zentrum und bereitet Königssicherheit vor.",
    "Ein zentraler Bauernzug schafft Raum und öffnet häufig Linien für Läufer oder Dame, kann aber auch Felder schwächen.",
  ],
});

const family = ({
  overview,
  pawnStructures,
  development,
  whitePlans,
  blackPlans,
  commonMistakes,
  explanations,
}) => Object.freeze({
  overview,
  pawnStructures,
  development,
  whitePlans,
  blackPlans,
  commonMistakes,
  explanations,
});

export const OPENING_FAMILY_KNOWLEDGE = Object.freeze({
  "Sicilian Defense": family({
    overview: "Die Sizilianische Verteidigung schafft sofort ein asymmetrisches Spiel: Weiß erhält häufig Raum, Schwarz aktives Gegenspiel.",
    pawnStructures: ["Schwarz tauscht oft den c-Bauern gegen den weißen d-Bauern und erhält dadurch die halboffene c-Linie.", "Weiße Raumvorteile im Zentrum stehen häufig schwarzem Druck am Damenflügel gegenüber."],
    development: ["Weiß entwickelt zügig, rochiert meist kurz und stützt das Zentrum.", "Schwarz entwickelt flexibel und bereitet den befreienden Vorstoß des d-Bauern vor."],
    whitePlans: ["Den Entwicklungsvorsprung nutzen und das Zentrum stabil halten.", "Je nach Struktur am Königsflügel angreifen oder die offene d-Linie kontrollieren."],
    blackPlans: ["Über die c-Linie und am Damenflügel Gegenspiel erzeugen.", "Das weiße Zentrum im richtigen Moment mit einem Bauernhebel angreifen."],
    commonMistakes: ["Als Weiß zu früh angreifen und dabei die Entwicklung vernachlässigen.", "Als Schwarz passiv bleiben, sodass der weiße Raumvorteil ohne Gegenspiel bestehen bleibt."],
    explanations: ["Der frühe c-Bauernzug greift das Zentrum von der Seite an und vermeidet eine vollkommen symmetrische Stellung.", "Die ungleichen Bauernstrukturen erklären, warum beide Seiten oft an verschiedenen Flügeln spielen."],
  }),
  "Ruy Lopez": family({
    overview: "Die Spanische Partie verbindet ruhigen Entwicklungsaufbau mit langfristigem Druck auf das schwarze Zentrum.",
    pawnStructures: ["Häufig bleibt das Zentrum zunächst gespannt oder geschlossen.", "Nach zentralen Abtäuschen entstehen oft offene Linien und ein Kampf um den e-Bauern."],
    development: ["Weiß entwickelt den Königsläufer aktiv, rochiert und bereitet den zentralen Durchbruch vor.", "Schwarz sichert den e-Bauern, entwickelt den Damenflügel und sucht einen befreienden Zentrumsvorstoß."],
    whitePlans: ["Den Druck auf das Zentrum erhöhen und die Figuren vor dem Öffnen der Stellung verbessern.", "In geschlossenen Strukturen Raum am Königsflügel gewinnen."],
    blackPlans: ["Den Damenflügel aktivieren und den weißen Läufer zurückdrängen.", "Sich im Zentrum befreien, bevor Weiß ungestört aufbauen kann."],
    commonMistakes: ["Den gefesselten Springer mit einem sofort gewonnenen Bauern verwechseln.", "Zu früh im Zentrum öffnen, obwohl die eigene Entwicklung zurückliegt."],
    explanations: ["Der Läuferzug erhöht indirekt den Druck auf den e-Bauern, weil er dessen wichtigsten Verteidiger bindet.", "Der ruhige Aufbau soll erst alle Figuren verbessern und dann das Zentrum öffnen."],
  }),
  "French Defense": family({
    overview: "Die Französische Verteidigung gibt Schwarz eine feste Basis, überlässt Weiß aber häufig mehr Raum.",
    pawnStructures: ["Geschlossene Bauernketten zeigen oft zum Königsflügel für Weiß und zum Damenflügel für Schwarz.", "Schwarz greift die weiße Bauernkette typischerweise an ihrer Basis an."],
    development: ["Weiß nutzt den Raum und entwickelt mit Blick auf einen Königsangriff.", "Schwarz muss besonders den weißfeldrigen Läufer sinnvoll ins Spiel bringen."],
    whitePlans: ["Den Raumvorteil sichern und am Königsflügel angreifen.", "Die Bauernkette stützen, ohne die Entwicklung zu verlangsamen."],
    blackPlans: ["Das weiße Zentrum mit Bauernhebeln angreifen.", "Am Damenflügel Gegenspiel schaffen und den schlechten Läufer verbessern."],
    commonMistakes: ["Als Weiß nur Bauern vorzuschieben und die Figuren zurückzulassen.", "Als Schwarz den eingesperrten Damenläufer dauerhaft ohne Aufgabe zu lassen."],
    explanations: ["Der e-Bauer stützt den späteren Kampf gegen das weiße Zentrum.", "Die geschlossene Mitte lenkt das Spiel häufig auf beide Flügel."],
  }),
  "Queen's Gambit Declined": family({
    overview: "Im abgelehnten Damengambit hält Schwarz das Zentrum fest, während Weiß Raum und langfristigen Druck erhält.",
    pawnStructures: ["Die schwarze Bauernkette ist solide, kann aber den Damenläufer einschränken.", "Nach einem zentralen Tausch entsteht häufig eine Karlsbader Struktur mit klaren Flügelplänen."],
    development: ["Weiß entwickelt harmonisch und erhöht den Druck auf das Zentrum.", "Schwarz sucht einen aktiven Platz für den Damenläufer und bereitet einen befreienden Bauernhebel vor."],
    whitePlans: ["Am Damenflügel eine Bauernmehrheit schwächen oder im Zentrum Raum gewinnen.", "Die bessere Beweglichkeit nutzen, bevor Schwarz sich befreit."],
    blackPlans: ["Im Zentrum rechtzeitig Gegenspiel schaffen.", "Die Figuren entlasten und den zunächst passiven Damenläufer aktivieren."],
    commonMistakes: ["Als Weiß ohne Vorbereitung Bauern am Damenflügel vorzuschieben.", "Als Schwarz nur die Stellung zu halten und den notwendigen Befreiungszug zu versäumen."],
    explanations: ["Schwarz verteidigt den Zentralbauern und akzeptiert dafür zunächst weniger Raum.", "Weiß opfert keinen Bauern dauerhaft, sondern lenkt einen schwarzen Zentralbauern vom Zentrum ab."],
  }),
  "Italian Game": family({
    overview: "Die Italienische Partie entwickelt schnell und richtet den Blick früh auf das empfindliche Feld vor dem schwarzen König.",
    pawnStructures: ["Das Zentrum kann rasch geöffnet werden oder mit einer ruhigeren, geschlossenen Kette bestehen bleiben.", "Der weiße c-Bauer unterstützt häufig einen späteren Aufbau eines starken Zentrums."],
    development: ["Beide Seiten bringen Leichtfiguren aktiv heraus und rochieren meist früh.", "Weiß entscheidet zwischen sofortigem Zentrumsspiel und einem langsameren Aufbau."],
    whitePlans: ["Das Zentrum unter günstigen Umständen öffnen.", "Mit vollständiger Entwicklung Druck am Königsflügel aufbauen."],
    blackPlans: ["Die Stellung ausgleichen, indem das weiße Zentrum angegriffen wird.", "Aktive Gegenchancen im Zentrum oder am Damenflügel suchen."],
    commonMistakes: ["Nur auf einen schnellen Angriff gegen den König zu hoffen.", "Ein taktisches Opfer zu spielen, bevor genügend Figuren beteiligt sind."],
    explanations: ["Der Läufer steht aktiv und zielt auf ein anfangs nur vom König gedecktes Feld.", "Schnelle Entwicklung macht ein späteres Öffnen des Zentrums wirkungsvoll."],
  }),
  "English Opening": family({
    overview: "Die Englische Eröffnung kontrolliert das Zentrum zunächst von der Seite und hält viele Bauernstrukturen offen.",
    pawnStructures: ["Oft entstehen Strukturen einer Sizilianischen Verteidigung mit vertauschten Farben.", "Ein weißes Fianchetto unterstützt langfristigen Druck auf der langen Diagonale."],
    development: ["Weiß entwickelt flexibel und legt sich im Zentrum nicht sofort fest.", "Schwarz entscheidet zwischen eigenem Zentrum, symmetrischem Aufbau und Gegenspiel am Damenflügel."],
    whitePlans: ["Das Zentrum später im passenden Moment besetzen oder angreifen.", "Druck auf der langen Diagonale und am Damenflügel aufbauen."],
    blackPlans: ["Weiße Kontrolle über die hellen Zentralfelder bestreiten.", "Die zusätzliche Flexibilität durch einen aktiven zentralen Aufbau begrenzen."],
    commonMistakes: ["So zurückhaltend spielen, dass Schwarz ungestört das ganze Zentrum besetzt.", "Die flexible Zugfolge mit Planlosigkeit verwechseln."],
    explanations: ["Der Flügelbauer kontrolliert ein wichtiges Zentralfeld, ohne einen Zentralbauern festzulegen.", "Der Aufbau gewinnt seinen Wert durch den späteren Übergang in eine passende Bauernstruktur."],
  }),
  "King's Gambit Accepted": family({
    overview: "Im angenommenen Königsgambit gibt Weiß Material für schnelle Entwicklung, offene Linien und Angriffschancen.",
    pawnStructures: ["Die f-Linie kann sich früh öffnen und beide Könige werden taktisch verwundbar.", "Schwarz besitzt einen Mehrbauern, muss ihn aber gegen den weißen Entwicklungsvorsprung sichern."],
    development: ["Weiß muss Figuren schnell ins Spiel bringen und den König schützen.", "Schwarz entwickelt mit Tempo und vermeidet unnötige Bauernzüge zur Verteidigung der Beute."],
    whitePlans: ["Die offenen Linien und den Entwicklungsvorsprung sofort nutzen.", "Das Zentrum öffnen, solange schwarze Figuren noch unentwickelt sind."],
    blackPlans: ["Den Angriff neutralisieren und erst danach den Mehrbauern verwerten.", "Figuren tauschen und den weißen König im Blick behalten."],
    commonMistakes: ["Als Weiß weitere Bauern opfern, ohne neue Figuren in den Angriff zu bringen.", "Als Schwarz den Mehrbauern um jeden Preis halten und dabei die Entwicklung verlieren."],
    explanations: ["Der geopferte Bauer öffnet eine Linie und lenkt einen schwarzen Bauern vom Zentrum weg.", "Das Gambit ist nur dann sinnvoll, wenn der Zeitgewinn in echte Figurenaktivität umgesetzt wird."],
  }),
  "King's Gambit Declined": family({
    overview: "Beim abgelehnten Königsgambit nimmt Schwarz den Bauern nicht und versucht, das Zentrum auf andere Weise zu stabilisieren.",
    pawnStructures: ["Weiß hat Raum am Königsflügel, aber der vorgerückte f-Bauer kann Felder am eigenen König schwächen.", "Das Zentrum bleibt häufig länger geschlossen als in der angenommenen Variante."],
    development: ["Weiß entwickelt schnell und sucht die passende Öffnung des Zentrums.", "Schwarz stellt den König sicher und greift den weißen Aufbau im Zentrum an."],
    whitePlans: ["Den Raumgewinn in Aktivität umwandeln.", "Die Schwächen am eigenen König durch schnelle Entwicklung ausgleichen."],
    blackPlans: ["Den weißen f-Bauern als mögliches Angriffsziel behandeln.", "Das Zentrum öffnen, wenn der weiße König noch unsicher steht."],
    commonMistakes: ["Als Weiß automatisch einen Angriff erzwingen, obwohl Schwarz solide steht.", "Als Schwarz die weiße Raumkontrolle ohne Gegenspiel hinnehmen."],
    explanations: ["Schwarz verzichtet auf Materialgewinn, um dem weißen Angriff weniger Tempo zu geben.", "Der weiße f-Bauer unterstützt das Zentrum, lockert aber zugleich die Königsstellung."],
  }),
  "King's Indian Defense": family({
    overview: "Die Königsindische Verteidigung erlaubt Weiß ein breites Zentrum und greift dieses später dynamisch an.",
    pawnStructures: ["Geschlossene Bauernketten führen oft zu weißem Raum am Damenflügel und schwarzem Spiel am Königsflügel.", "Der schwarze e-Bauernhebel greift die Spitze des weißen Zentrums an."],
    development: ["Schwarz fianchettiert den Königsläufer und rochiert früh.", "Weiß entwickelt hinter dem Bauernzentrum und entscheidet, an welchem Flügel Raum gewonnen wird."],
    whitePlans: ["Am Damenflügel Raum gewinnen und dort Linien öffnen.", "Das Zentrum stützen oder im richtigen Moment selbst öffnen."],
    blackPlans: ["Das weiße Zentrum angreifen und am Königsflügel Initiative erzeugen.", "Den schwarzfeldrigen Läufer auf der langen Diagonale wirksam machen."],
    commonMistakes: ["Als Weiß den Damenflügel öffnen, ohne schwarzen Königsangriff zu beachten.", "Als Schwarz am Königsflügel angreifen, bevor das Zentrum festgelegt ist."],
    explanations: ["Schwarz kontrolliert das Zentrum zunächst mit Figuren und fordert die weißen Bauern später heraus.", "Die Richtung der Bauernketten erklärt die typischen Angriffsseiten."],
  }),
  "Caro-Kann Defense": family({
    overview: "Caro-Kann ist eine solide Verteidigung, die das weiße Zentrum angreift und den Damenläufer meist außerhalb der Bauernkette entwickelt.",
    pawnStructures: ["Schwarz erhält häufig eine feste Struktur ohne den eingesperrten Läufer der Französischen Verteidigung.", "Weiß besitzt in vielen Varianten mehr Raum und versucht, diesen langfristig zu nutzen."],
    development: ["Schwarz entwickelt den Damenläufer früh und schließt danach die Entwicklung ab.", "Weiß nutzt Raum, entwickelt natürlich und vermeidet überhastete Angriffe."],
    whitePlans: ["Den Raumvorteil behalten und schwarze Befreiungszüge erschweren.", "Am Königsflügel oder im Zentrum Druck aufbauen."],
    blackPlans: ["Die solide Stellung durch einen rechtzeitigen Bauernhebel aktivieren.", "Figuren tauschen, ohne in vollständige Passivität zu geraten."],
    commonMistakes: ["Als Weiß die solide Stellung mit unvorbereiteten Opfern öffnen wollen.", "Als Schwarz nur abzutauschen und jede aktive Möglichkeit auszulassen."],
    explanations: ["Der c-Bauer stützt den Angriff auf das weiße Zentrum, ohne den Damenläufer einzuschließen.", "Schwarz nimmt zunächst etwas weniger Raum in Kauf und zielt auf eine gesunde Entwicklung."],
  }),
  "Nimzo-Indian Defense": family({
    overview: "Die Nimzo-Indische Verteidigung verbindet schnelle Entwicklung mit Druck gegen das weiße Zentrum und mögliche Strukturschwächen.",
    pawnStructures: ["Weiß kann ein starkes Läuferpaar erhalten, dafür aber verdoppelte c-Bauern akzeptieren.", "Die Kontrolle über zentrale dunkle Felder ist häufig wichtiger als sofortiger Raumgewinn."],
    development: ["Schwarz entwickelt mit Tempo und bindet einen Verteidiger des Zentrums.", "Weiß entscheidet zwischen Strukturerhalt, Läuferpaar und kräftigem Zentrum."],
    whitePlans: ["Das Läuferpaar und den Raumvorteil aktiv nutzen.", "Strukturschwächen durch Figurenaktivität ausgleichen."],
    blackPlans: ["Druck gegen die c-Bauern und zentrale Felder aufbauen.", "Das weiße Zentrum angreifen, bevor es sich vollständig stabilisiert."],
    commonMistakes: ["Als Weiß verdoppelte Bauern automatisch als verloren ansehen.", "Als Schwarz den Läufer abtauschen, ohne anschließend die geschwächte Struktur anzugreifen."],
    explanations: ["Die Fesselung erschwert den Aufbau eines großen weißen Bauernzentrums.", "Der mögliche Läufertausch tauscht eine Figur gegen langfristige Kontrolle und Strukturziele."],
  }),
  "Queen's Pawn Game": family({
    overview: "Das Damenbauernspiel führt meist zu einem stabilen Zentrum und einem eher strategischen Aufbau.",
    pawnStructures: ["Weiße und schwarze d-Bauern bilden den Kern des Zentrums.", "Die c-Bauern entscheiden häufig, ob das Zentrum gespannt, geschlossen oder geöffnet wird."],
    development: ["Beide Seiten entwickeln mit Blick auf die Unterstützung oder den Angriff des d-Bauern.", "Der Damenläufer braucht oft einen bewusst vorbereiteten Entwicklungsweg."],
    whitePlans: ["Mehr Raum im Zentrum gewinnen oder den schwarzen Zentralbauern unter Druck setzen.", "Die Figuren harmonisch hinter der Bauernstruktur aufstellen."],
    blackPlans: ["Das weiße Zentrum mit einem seitlichen Bauernhebel angreifen.", "Den eigenen Damenläufer aktivieren und vollständig ausgleichen."],
    commonMistakes: ["Den Damenläufer durch unbedachte Bauernzüge dauerhaft einsperren.", "Den Zentrumskampf zugunsten zufälliger Flügelzüge vernachlässigen."],
    explanations: ["Der Damenbauer kontrolliert ein Zentralfeld und öffnet zugleich die Diagonale des Damenläufers.", "Der Aufbau ist weniger taktisch erzwungen, verlangt aber einen klaren Plan für die c-Bauern."],
  }),
  "Dutch Defense": family({
    overview: "Die Holländische Verteidigung kontrolliert das e-Zentrum und strebt aktives Spiel am Königsflügel an.",
    pawnStructures: ["Der vorgeschobene f-Bauer gewinnt Raum, schwächt aber Felder rund um den schwarzen König.", "Je nach Aufbau entsteht eine geschlossene Kette oder eine flexible Steinwallstruktur."],
    development: ["Schwarz entwickelt den Königsspringer und entscheidet zwischen Fianchetto und kompaktem Königsflügel.", "Weiß entwickelt ruhig und sucht Druck gegen die geschwächten dunklen Felder."],
    whitePlans: ["Das schwarze Zentrum und die Königsfelder angreifen.", "Am Damenflügel Raum gewinnen, falls Schwarz am Königsflügel gebunden ist."],
    blackPlans: ["Mit Raum und Figuren am Königsflügel Initiative aufbauen.", "Das Zentrum stabil halten und den weißfeldrigen Läufer sinnvoll entwickeln."],
    commonMistakes: ["Als Schwarz den Königsflügel öffnen, bevor der König sicher ist.", "Als Weiß den schwarzen Raumgewinn unterschätzen und zu passiv reagieren."],
    explanations: ["Der f-Bauer kontrolliert ein wichtiges Zentralfeld und kündigt aktives Spiel an.", "Der Preis dafür sind gelockerte Felder, die sorgfältige Entwicklung verlangen."],
  }),
  "Semi-Slav Defense": family({
    overview: "Die Halbslawische Verteidigung baut ein sehr festes schwarzes Zentrum auf und bereitet später aktive Befreiung vor.",
    pawnStructures: ["Das schwarze Bauerndreieck hält das Zentrum, schränkt aber zunächst den Damenläufer ein.", "Nach einem zentralen Durchbruch kann die Stellung sehr scharf und offen werden."],
    development: ["Weiß entwickelt und bereitet einen starken Zentrumsaufbau vor.", "Schwarz muss den Damenläufer befreien und den richtigen Moment für den Zentrumskampf wählen."],
    whitePlans: ["Raum im Zentrum gewinnen und die schwarze Entwicklung erschweren.", "Die Spannung halten, bis ein Öffnen der Stellung die aktiveren Figuren begünstigt."],
    blackPlans: ["Sich mit einem zentralen Bauernhebel befreien.", "Den zunächst eingeschlossenen Damenläufer aktiv ins Spiel bringen."],
    commonMistakes: ["Als Weiß das Zentrum öffnen, bevor die Figuren bereitstehen.", "Als Schwarz die feste Struktur mit einer passiven Stellung verwechseln."],
    explanations: ["Der c-Bauer stützt den d-Bauern und gibt Schwarz eine sehr belastbare Basis.", "Die Solidität funktioniert nur, wenn Schwarz später aktiv gegen das weiße Zentrum vorgeht."],
  }),
  "Benoni Defense": family({
    overview: "Die Benoni-Verteidigung gibt Weiß Raum im Zentrum, während Schwarz dynamisches Gegenspiel am Damenflügel sucht.",
    pawnStructures: ["Weiß besitzt meist eine zentrale Bauernmehrheit und einen Raumvorteil.", "Schwarz erhält eine halboffene Linie und eine Bauernmehrheit am Damenflügel."],
    development: ["Schwarz fianchettiert häufig den Königsläufer und richtet ihn gegen das Zentrum.", "Weiß entwickelt hinter dem starken Zentrum und bereitet dessen Vormarsch vor."],
    whitePlans: ["Im Zentrum oder am Königsflügel mit dem Raumvorteil vorankommen.", "Schwarzes Gegenspiel am Damenflügel kontrollieren."],
    blackPlans: ["Die Damenflügelmehrheit mobilisieren und offene Linien nutzen.", "Das weiße Zentrum mit Figuren und Bauernhebeln unter Druck setzen."],
    commonMistakes: ["Als Weiß zu schnell Bauern vorzuschieben und rückständige Felder zu hinterlassen.", "Als Schwarz passiv warten, obwohl die Stellung aktives Gegenspiel verlangt."],
    explanations: ["Schwarz akzeptiert weniger Raum, um klare Angriffsziele und dynamische Linien zu erhalten.", "Der zentrale Raum ist ein Vorteil, muss aber durch Entwicklung abgesichert werden."],
  }),
  "Grünfeld Defense": family({
    overview: "Die Grünfeld-Verteidigung erlaubt Weiß ein großes Zentrum, um es anschließend aus der Entfernung anzugreifen.",
    pawnStructures: ["Weiße Zentralbauern gewinnen Raum, können aber zu Angriffszielen werden.", "Offene Diagonalen und Linien machen genaue Figurenaktivität besonders wichtig."],
    development: ["Schwarz fianchettiert den Königsläufer und greift das Zentrum mit mehreren Figuren an.", "Weiß entwickelt so, dass das breite Zentrum beweglich und ausreichend gedeckt bleibt."],
    whitePlans: ["Das Zentrum vorrücken oder stabilisieren und daraus Raum gewinnen.", "Den schwarzen Druck neutralisieren, bevor ein Flügelangriff beginnt."],
    blackPlans: ["Die weiße Bauernkette an ihrer Basis angreifen.", "Offene Linien und den lang wirkenden Läufer für aktives Gegenspiel nutzen."],
    commonMistakes: ["Als Weiß das eindrucksvolle Zentrum für unangreifbar halten.", "Als Schwarz Bauern angreifen, bevor genügend Figuren Druck ausüben."],
    explanations: ["Schwarz besetzt das Zentrum nicht sofort mit Bauern, sondern macht es zum Angriffsziel.", "Weiße Raumkontrolle und schwarze Figurenaktivität bilden den strategischen Kern."],
  }),
  "Queen's Gambit Accepted": family({
    overview: "Im angenommenen Damengambit gibt Schwarz das Zentrum vorübergehend frei und versucht, sich danach aktiv zu entwickeln.",
    pawnStructures: ["Der eroberte Flügelbauer ist meist weniger wichtig als der Kampf um das Zentrum.", "Weiß kann ein starkes Bauernzentrum aufbauen; Schwarz greift es später an."],
    development: ["Weiß entwickelt mit Raumgewinn und holt den Bauern meist ohne Hast zurück.", "Schwarz entwickelt schnell und bereitet einen Gegenschlag im Zentrum vor."],
    whitePlans: ["Das freie Zentrum besetzen und Entwicklungsvorsprung nutzen.", "Den Bauern zurückgewinnen, ohne dafür mehrere Tempi zu investieren."],
    blackPlans: ["Das weiße Zentrum angreifen und freie Figurenentwicklung erreichen.", "Den Mehrbauern nur halten, wenn dies keine Entwicklung kostet."],
    commonMistakes: ["Als Weiß sofort mit der Dame auf Bauernjagd gehen.", "Als Schwarz den zusätzlichen Bauern mit vielen weiteren Bauernzügen verteidigen."],
    explanations: ["Schwarz nimmt den Bauern, um das weiße Zentrum später direkt anzugreifen.", "Weiß erhält Zeit und Raum, wenn Schwarz versucht, den Flügelbauern dauerhaft festzuhalten."],
  }),
  "Alekhine Defense": family({
    overview: "Die Aljechin-Verteidigung lockt weiße Bauern nach vorn und versucht, das entstandene Zentrum später anzugreifen.",
    pawnStructures: ["Weiß erhält viel Raum, dessen Bauern aber auch Angriffsziele werden können.", "Schwarz besitzt weniger Raum und braucht aktive Hebel gegen die weiße Bauernkette."],
    development: ["Weiß sollte den Raumgewinn mit schneller Figurenentwicklung verbinden.", "Schwarz provoziert Bauernzüge, darf dabei aber nicht zu viele Tempi mit derselben Figur verlieren."],
    whitePlans: ["Das breite Zentrum stabilisieren und Raum in Aktivität umwandeln.", "Schwarze Befreiungszüge erschweren."],
    blackPlans: ["Die vorgerückten Bauern unter Druck setzen.", "Weiße Überdehnung ausnutzen und Linien für die eigenen Figuren öffnen."],
    commonMistakes: ["Als Weiß jeden möglichen Bauernzug spielen und die Entwicklung vergessen.", "Als Schwarz nur den Springer bewegen und den Rest der Armee zurücklassen."],
    explanations: ["Der Springer lädt Weiß bewusst zum Raumgewinn ein.", "Der Plan funktioniert nur, wenn das weiße Zentrum später tatsächlich angegriffen wird."],
  }),
  "Indian Defense": family({
    overview: "Indische Verteidigungen entwickeln zuerst eine Figur und halten die zentrale Bauernstruktur flexibel.",
    pawnStructures: ["Weiß darf häufig zunächst Raum mit Bauern gewinnen.", "Schwarz entscheidet später, ob das Zentrum direkt, mit einem Fianchetto oder durch Bauernhebel bestritten wird."],
    development: ["Schwarz kontrolliert das Zentrum mit Figuren und legt die Bauern erst später fest.", "Weiß baut Raum auf, muss aber die möglichen Gegenangriffe auf dieses Zentrum beachten."],
    whitePlans: ["Den Raumvorteil sichern und harmonisch entwickeln.", "Den passenden Aufbau gegen die konkrete schwarze Figurenstellung wählen."],
    blackPlans: ["Das weiße Zentrum rechtzeitig angreifen.", "Flexibilität in aktives Gegenspiel umwandeln, bevor Weiß alles stabilisiert."],
    commonMistakes: ["Als Weiß das große Zentrum ohne ausreichende Deckung vorschieben.", "Als Schwarz Flexibilität mit passivem Abwarten verwechseln."],
    explanations: ["Der frühe Springerzug kontrolliert das Zentrum, ohne die Bauernstruktur festzulegen.", "Schwarz lädt Weiß zum Raumgewinn ein und plant späteren Druck dagegen."],
  }),
  "Scotch Game": family({
    overview: "Die Schottische Partie öffnet das Zentrum früh und setzt auf schnelle, freie Figurenentwicklung.",
    pawnStructures: ["Der frühe zentrale Tausch löst die Symmetrie auf und schafft offene Linien.", "Isolierte oder vorgeschobene Zentralbauern können zu wichtigen Zielen werden."],
    development: ["Beide Seiten müssen Figuren schnell auf aktive Felder bringen.", "Damenaktionen sind nur sinnvoll, wenn sie nicht mehrere Entwicklungstempi kosten."],
    whitePlans: ["Den Raum und die offenen Linien für aktive Entwicklung nutzen.", "Schwarzen Druck gegen den Zentralbauern durch Figurenaktivität ausgleichen."],
    blackPlans: ["Das weiße Zentrum direkt angreifen.", "Mit Tempo entwickeln und die offene Stellung für Gegenspiel nutzen."],
    commonMistakes: ["In der offenen Mitte mit derselben Figur mehrfach ziehen.", "Einen Zentralbauern halten wollen, obwohl dadurch Entwicklung verloren geht."],
    explanations: ["Weiß öffnet das Zentrum sofort, damit der Anzugsvorteil als Entwicklungsvorsprung wirken kann.", "Die offenen Linien bestrafen unentwickelte Figuren und einen unsicheren König schneller."],
  }),
  "Queen's Indian Defense": family({
    overview: "Die Damenindische Verteidigung kontrolliert das Zentrum mit Figuren und richtet langfristigen Druck gegen die weißen Zentralfelder.",
    pawnStructures: ["Schwarz hält die Bauernstruktur flexibel und greift besonders die dunklen Zentralfelder an.", "Weiß besitzt meist etwas mehr Raum, aber kein unangefochtenes Bauernzentrum."],
    development: ["Schwarz fianchettiert den Damenläufer und entwickelt sehr harmonisch.", "Weiß sucht einen Aufbau, der Raum sichert und die lange Diagonale begrenzt."],
    whitePlans: ["Raumvorteil und Läuferpaar nutzen.", "Das Zentrum stabilisieren und erst dann am Flügel expandieren."],
    blackPlans: ["Druck auf das weiße Zentrum und die c-Linie ausüben.", "Durch gute Figurenfelder vollständig ausgleichen."],
    commonMistakes: ["Als Weiß die lange Diagonale und den Druck auf das Zentrum unterschätzen.", "Als Schwarz zu passiv bleiben und die flexible Stellung nicht aktivieren."],
    explanations: ["Der fianchettierte Läufer greift das Zentrum aus großer Entfernung an.", "Schwarz setzt auf Kontrolle und Entwicklung statt auf eine frühe feste Bauernkette."],
  }),
  "Slav Defense": family({
    overview: "Die Slawische Verteidigung stützt den schwarzen Zentralbauern, ohne den Damenläufer einzuschließen.",
    pawnStructures: ["Die schwarze c-d-Bauernkette ist fest und lässt den Damenläufer zunächst frei.", "Zentrale Abtäusche können eine symmetrische, aber strategisch reichhaltige Struktur erzeugen."],
    development: ["Schwarz entwickelt den Damenläufer aktiv, bevor die Stellung geschlossen wird.", "Weiß erhöht den Druck im Zentrum und nutzt den kleinen Raumvorteil."],
    whitePlans: ["Schwarze Befreiungszüge erschweren und Raum sichern.", "Am Damenflügel Druck gegen die Bauernstruktur aufbauen."],
    blackPlans: ["Sich im Zentrum befreien und alle Figuren aktiv entwickeln.", "Weißen Druck durch rechtzeitige Vereinfachung neutralisieren."],
    commonMistakes: ["Als Weiß die solide Stellung ohne Vorbereitung erzwingen wollen.", "Als Schwarz den Damenläufer außerhalb der Bauernkette platzieren, wo er durch Bauernzüge Tempo verliert."],
    explanations: ["Der c-Bauer verteidigt das Zentrum und bewahrt zugleich die natürliche Diagonale des Damenläufers.", "Schwarz strebt eine gesunde Struktur an, muss aber rechtzeitig aktiv werden."],
  }),
  "Petrov's Defense": family({
    overview: "Die Russische Verteidigung beantwortet den weißen Zentralangriff symmetrisch und setzt auf genaue, aktive Verteidigung.",
    pawnStructures: ["Frühe zentrale Abtäusche führen oft zu einer offenen und ausgeglichenen Struktur.", "Kleine Entwicklungsvorteile sind wichtiger als große Raumunterschiede."],
    development: ["Beide Seiten entwickeln schnell und achten auf taktische Angriffe gegen die zentralen Figuren.", "Schwarz darf die Symmetrie nicht mit automatischem Nachziehen verwechseln."],
    whitePlans: ["Mit etwas mehr Raum und dem ersten Zug kleine Initiative behalten.", "Schwarze Figuren durch präzise Entwicklung unter Druck setzen."],
    blackPlans: ["Das weiße Zentrum direkt angreifen und sicher ausgleichen.", "Aktive Figuren statt bloßer Verteidigung anstreben."],
    commonMistakes: ["Blind symmetrische Züge kopieren, obwohl sich die Taktik unterscheidet.", "Mit einem Springer Bauern verfolgen und dabei in eine Fesselung geraten."],
    explanations: ["Schwarz verteidigt den angegriffenen Bauern nicht passiv, sondern greift den weißen Zentralbauern ebenfalls an.", "Die frühe Symmetrie macht genaue Zugreihenfolge besonders wichtig."],
  }),
  "Four Knights Game": family({
    overview: "Das Vierspringerspiel entwickelt alle Springer früh und schafft eine solide, übersichtliche Ausgangslage.",
    pawnStructures: ["Das Zentrum bleibt zunächst symmetrisch und kann später mit einem d-Bauernzug geöffnet werden.", "Nach Abtäuschen entstehen oft ruhige Strukturen mit kleinen positionellen Unterschieden."],
    development: ["Beide Seiten erfüllen schnell die grundlegenden Entwicklungsaufgaben.", "Die Läuferentwicklung entscheidet, ob das Spiel ruhig oder taktisch wird."],
    whitePlans: ["Den ersten Zug für etwas mehr Raum oder Druck im Zentrum nutzen.", "Eine günstige Öffnung des Zentrums vorbereiten."],
    blackPlans: ["Vollständig ausgleichen und weiße Zentrumsvorstöße kontrollieren.", "Nicht nur spiegeln, sondern aktive Felder für die Läufer finden."],
    commonMistakes: ["Die solide Stellung ohne Plan weiterspielen.", "Das Zentrum öffnen, während der König noch nicht sicher ist."],
    explanations: ["Die Springer kontrollieren zentrale Felder und bereiten die Rochade vor.", "Der natürliche Aufbau ist sicher, verlangt danach aber eine bewusste Entscheidung im Zentrum."],
  }),
  "Zukertort Opening": family({
    overview: "Die Zukertort-Eröffnung beginnt flexibel mit Figurenkontrolle und legt die Bauernstruktur erst später fest.",
    pawnStructures: ["Ein Damenfianchetto unterstützt häufig Druck auf die lange Diagonale.", "Weiße Bauern können später passend mit einem c- oder d-Bauernzug das Zentrum angreifen."],
    development: ["Weiß entwickelt zuerst den Königsspringer und behält viele Übergänge offen.", "Schwarz kann Raum besetzen, muss diesen aber ausreichend stützen."],
    whitePlans: ["Das schwarze Zentrum aus der Entfernung angreifen.", "Je nach schwarzem Aufbau in ein Damenbauern- oder Englisch-System übergehen."],
    blackPlans: ["Den flexiblen Aufbau mit gesundem Raumgewinn beantworten.", "Weiße Kontrolle über zentrale Felder begrenzen."],
    commonMistakes: ["Flexibilität als Grund für planlose Wartezüge verwenden.", "Dem Gegner das Zentrum überlassen, ohne es später anzugreifen."],
    explanations: ["Der Springer entwickelt sich, kontrolliert das Zentrum und verrät noch wenig über die Bauernstruktur.", "Der Aufbau lebt von passenden Übergängen, nicht von einer starren Zugfolge."],
  }),
  "Scandinavian Defense": family({
    overview: "Die Skandinavische Verteidigung greift den weißen Zentralbauern sofort an und klärt die Stellung früh.",
    pawnStructures: ["Nach dem frühen Tausch erhält Weiß meist Raum und Schwarz eine klare, solide Struktur.", "Schwarz übt später Druck gegen das Zentrum aus, muss aber oft Zeit für die Dame investieren."],
    development: ["Weiß entwickelt mit Tempo, wenn die schwarze Dame früh im Spiel steht.", "Schwarz stellt die Dame sicher und schließt die Entwicklung ohne weitere Zeitverluste ab."],
    whitePlans: ["Entwicklungsvorsprung und Raum nutzen.", "Die schwarze Dame nur dann angreifen, wenn dabei eine eigene Figur sinnvoll entwickelt wird."],
    blackPlans: ["Das weiße Zentrum unter Druck setzen und eine feste Stellung aufbauen.", "Verlorene Tempi durch klare Figurenfelder ausgleichen."],
    commonMistakes: ["Als Weiß nur die Dame jagen und dabei eigene Figuren schlecht platzieren.", "Als Schwarz die Dame mehrfach ohne konkreten Nutzen bewegen."],
    explanations: ["Schwarz fordert den weißen Zentralbauern sofort heraus.", "Der frühe Damenkontakt ist spielbar, macht effiziente Entwicklung aber besonders wichtig."],
  }),
  "Philidor Defense": family({
    overview: "Die Philidor-Verteidigung stützt den schwarzen e-Bauern solide, gibt Weiß aber häufig mehr Raum.",
    pawnStructures: ["Die schwarze Bauernkette ist fest, kann aber Figuren einengen.", "Weiß besitzt oft ein starkes Zentrum und sucht eine günstige Öffnung."],
    development: ["Schwarz muss besonders den Königsläufer und den Damenflügel aktivieren.", "Weiß entwickelt natürlich und vermeidet es, das Zentrum voreilig zu überdehnen."],
    whitePlans: ["Den Raumvorteil sichern und schwarze Passivität ausnutzen.", "Das Zentrum öffnen, wenn die Entwicklung abgeschlossen ist."],
    blackPlans: ["Mit einem Bauernhebel gegen das weiße Zentrum vorgehen.", "Die enge Stellung durch aktive Figurenmanöver entlasten."],
    commonMistakes: ["Als Schwarz nur den e-Bauern verteidigen und alle Figuren einsperren.", "Als Weiß den Raumvorteil für einen sofortigen Gewinn halten."],
    explanations: ["Der d-Bauer gibt dem e-Bauern eine feste Stütze.", "Die Sicherheit kostet Beweglichkeit, deshalb braucht Schwarz einen späteren Befreiungsplan."],
  }),
  "Réti Opening": family({
    overview: "Die Réti-Eröffnung kontrolliert das Zentrum mit Figuren und greift ein gegnerisches Bauernzentrum später an.",
    pawnStructures: ["Ein Fianchetto schafft langfristigen Druck auf der langen Diagonale.", "Die weißen Zentralbauern bleiben zunächst flexibel und reagieren auf den schwarzen Aufbau."],
    development: ["Weiß entwickelt den Königsspringer und Königsläufer früh.", "Schwarz darf Raum nehmen, muss aber auf Angriffe gegen die Bauernkette vorbereitet sein."],
    whitePlans: ["Das schwarze Zentrum mit Flügelbauern und Figuren unter Druck setzen.", "Zum passenden Zeitpunkt selbst im Zentrum Fuß fassen."],
    blackPlans: ["Den Raumvorteil stabilisieren und harmonisch entwickeln.", "Weiße Bauernhebel kontrollieren, bevor sie das Zentrum untergraben."],
    commonMistakes: ["Als Weiß das Zentrum nur beobachten und niemals angreifen.", "Als Schwarz zu viele Bauern vorzuschieben und dadurch Ziele zu schaffen."],
    explanations: ["Der Springer beeinflusst das Zentrum, ohne eine Bauernstruktur festzulegen.", "Der hypermoderne Aufbau erlaubt gegnerischen Raum nur mit dem Plan, ihn später anzugreifen."],
  }),
  "Nimzowitsch Defense": family({
    overview: "Die Nimzowitsch-Verteidigung entwickelt früh den Damenspringer und hält mehrere zentrale Gegenschläge offen.",
    pawnStructures: ["Weiß kann Raum im Zentrum gewinnen.", "Schwarz versucht, das weiße Zentrum flexibel mit Bauern oder Figuren anzugreifen."],
    development: ["Der frühe Damenspringer übt Druck aus, kann aber den c-Bauern behindern.", "Weiß entwickelt hinter dem Zentrum und schützt es vor Gegenangriffen."],
    whitePlans: ["Raum sichern und schwarze Gegenschläge begrenzen.", "Die ungewöhnliche schwarze Zugfolge mit ruhiger Entwicklung beantworten."],
    blackPlans: ["Das weiße Zentrum provozieren und anschließend angreifen.", "Den Damenspringer so einsetzen, dass er die übrige Entwicklung nicht blockiert."],
    commonMistakes: ["Als Schwarz den Springer mehrfach ziehen und Entwicklung verlieren.", "Als Weiß die ungewöhnliche Eröffnung sofort taktisch widerlegen wollen."],
    explanations: ["Schwarz kontrolliert ein Zentralfeld mit einer Figur statt mit einem Bauern.", "Die Flexibilität hat den Preis, dass der natürliche c-Bauernzug zunächst blockiert sein kann."],
  }),
  "Bishop's Opening": family({
    overview: "Die Läufereröffnung entwickelt sofort eine Figur, übt Druck auf den Königsflügel aus und hält den Königsspringer flexibel.",
    pawnStructures: ["Das Zentrum kann in ein Italienisches Spiel übergehen oder mit einem f-Bauernaufbau schärfer werden.", "Die zunächst offene Zugfolge erlaubt viele Übergänge."],
    development: ["Weiß aktiviert den Königsläufer und entscheidet später über Springer und Zentralbauern.", "Schwarz entwickelt ruhig und sichert das empfindliche Königsfeld."],
    whitePlans: ["Schnell rochieren und das Zentrum passend öffnen.", "Den aktiven Läufer mit weiteren entwickelten Figuren unterstützen."],
    blackPlans: ["Den frühen Läuferdruck neutralisieren und selbst das Zentrum bestreiten.", "Weiße Flexibilität durch einen gesunden Aufbau begrenzen."],
    commonMistakes: ["Den Läufer allein angreifen lassen, ohne weitere Figuren zu entwickeln.", "Früh Bauern am Königsflügel vorzuschieben und den eigenen König zu schwächen."],
    explanations: ["Der Läufer entwickelt sich mit Blick auf ein anfangs empfindliches Feld.", "Weiß legt die Springerstellung noch nicht fest und behält flexible Übergänge."],
  }),
  "Vienna Game": family({
    overview: "Die Wiener Partie entwickelt den Damenspringer früh und ermöglicht sowohl ruhige Zentrumskontrolle als auch scharfes Königsflügelspiel.",
    pawnStructures: ["Weiß stützt den e-Bauern und kann später mit dem f-Bauern Raum gewinnen.", "Schwarz sucht aktiven Gegendruck im Zentrum, bevor Weiß einen Angriff aufbaut."],
    development: ["Weiß entwickelt den Königsläufer und bringt den König in Sicherheit.", "Schwarz stellt das Zentrum solide auf und nutzt mögliche weiße Felderschwächungen."],
    whitePlans: ["Ein starkes Zentrum aufbauen oder am Königsflügel Raum gewinnen.", "Den Angriff erst nach ausreichender Entwicklung beginnen."],
    blackPlans: ["Das weiße Zentrum direkt bestreiten.", "Gelockerte Felder am weißen König ausnutzen."],
    commonMistakes: ["Als Weiß den f-Bauern ohne Entwicklung und Königssicherheit vorschieben.", "Als Schwarz zu passiv bleiben und Weiß einen kostenlosen Angriffsaufbau erlauben."],
    explanations: ["Der Damenspringer stützt das Zentrum und hält verschiedene Angriffsideen offen.", "Der flexible Aufbau kann ruhig oder scharf werden, abhängig vom späteren f-Bauernzug."],
  }),
  "Modern Defense": family({
    overview: "Die Moderne Verteidigung lässt Weiß zunächst Raum und greift das Zentrum später mit Figuren und Bauernhebeln an.",
    pawnStructures: ["Weiß baut oft ein breites Bauernzentrum auf.", "Der schwarze Königsfianchetto erzeugt Druck gegen die zentralen dunklen Felder."],
    development: ["Schwarz entwickelt den Königsläufer früh, legt den Damenspringer aber oft flexibel fest.", "Weiß verbindet Raumgewinn mit schneller Entwicklung."],
    whitePlans: ["Das Zentrum stabil halten und schwarzen Gegendruck begrenzen.", "Den Raumvorteil für einen Angriff nutzen, ohne sich zu überdehnen."],
    blackPlans: ["Das weiße Zentrum an seiner Basis angreifen.", "Mit flexiblen Bauernhebeln Gegenspiel an Zentrum oder Damenflügel erzeugen."],
    commonMistakes: ["Als Weiß nur Bauern ziehen und Figuren unentwickelt lassen.", "Als Schwarz dem weißen Zentrum zu lange freien Lauf lassen."],
    explanations: ["Schwarz kontrolliert das Zentrum zunächst aus der Entfernung.", "Der Aufbau setzt darauf, dass ein großes Bauernzentrum auch klare Angriffsziele bietet."],
  }),
  "King's Pawn Game": family({
    overview: "Das König Bauernspiel öffnet Linien für Dame und Königsläufer und beansprucht sofort das Zentrum.",
    pawnStructures: ["Der e-Bauer bildet den ersten Stützpunkt im Zentrum.", "Die spätere Stellung hängt stark davon ab, ob Schwarz symmetrisch antwortet oder das Zentrum von der Seite angreift."],
    development: ["Der Königsspringer und Königsläufer können schnell aktiv werden.", "Beide Seiten sollten die offene e-Linie und die Sicherheit des Königs beachten."],
    whitePlans: ["Den Raum im Zentrum für schnelle Entwicklung nutzen.", "Die Rochade vorbereiten und erst danach einen konkreten Angriff beginnen."],
    blackPlans: ["Das weiße Zentrum direkt oder seitlich bestreiten.", "Ohne Zeitverlust entwickeln und den weißen Anzugsvorteil neutralisieren."],
    commonMistakes: ["Die offene Dame zu früh in den Kampf schicken.", "Nur den e-Bauern verteidigen und die übrige Entwicklung vernachlässigen."],
    explanations: ["Der Königbauer kontrolliert zwei Zentralfelder und öffnet zwei Figuren den Weg.", "Der Zug schafft sofort Raum, legt aber auch die zentrale Bauernstruktur früh fest."],
  }),
  "Catalan Opening": family({
    overview: "Die Katalanische Eröffnung verbindet ein Damenbauernzentrum mit einem Königsfianchetto und langfristigem Druck auf der langen Diagonale.",
    pawnStructures: ["Weiß besitzt häufig Raum im Zentrum und Druck gegen den schwarzen Damenflügel.", "Schwarz kann den c-Bauern nehmen, muss dann aber die Entwicklung und die lange Diagonale beachten."],
    development: ["Weiß fianchettiert den Königsläufer und rochiert sicher.", "Schwarz entwickelt den Damenflügel sorgfältig und sucht aktive Befreiung."],
    whitePlans: ["Langfristigen Druck auf der Diagonale und gegen den Damenflügel aufbauen.", "Das Zentrum stabil halten und Figurenaktivität über Material stellen."],
    blackPlans: ["Die weiße Diagonale begrenzen und sich im Zentrum befreien.", "Einen gewonnenen Bauern nur halten, wenn die Figuren dabei aktiv bleiben."],
    commonMistakes: ["Als Weiß den zurückgewinnbaren Bauern wichtiger als Entwicklung behandeln.", "Als Schwarz Material festhalten und auf dunklen Feldern eingeengt werden."],
    explanations: ["Das Fianchetto verstärkt den Druck auf den Damenflügel aus großer Entfernung.", "Weiß kombiniert Zentrumskontrolle mit langfristiger Läuferaktivität."],
  }),
  "Bird Opening": family({
    overview: "Die Bird-Eröffnung kontrolliert das e-Zentrum und gewinnt Raum am Königsflügel, lockert dabei aber die eigene Königsstellung.",
    pawnStructures: ["Der f-Bauer stützt häufig eine Steinwallstruktur.", "Dunkle Felder rund um den weißen König können zu langfristigen Schwächen werden."],
    development: ["Weiß entwickelt den Königsspringer und entscheidet zwischen Fianchetto und kompaktem Zentrum.", "Schwarz greift das Zentrum an und achtet auf die gelockerten Königsfelder."],
    whitePlans: ["Raum am Königsflügel nutzen und einen kontrollierten Angriff vorbereiten.", "Den problematischen Damenläufer aktiv entwickeln."],
    blackPlans: ["Das weiße Zentrum und die dunklen Königsfelder unter Druck setzen.", "Am Damenflügel oder im Zentrum Gegenspiel schaffen."],
    commonMistakes: ["Als Weiß sofort am Königsflügel stürmen, bevor der König sicher ist.", "Als Schwarz den ungewöhnlichen Aufbau unterschätzen und ohne Zentrumskontrolle spielen."],
    explanations: ["Der f-Bauer kontrolliert ein Zentralfeld und kündigt Raumgewinn am Königsflügel an.", "Der aktive Plan verlangt besondere Aufmerksamkeit für die eigene Königssicherheit."],
  }),
  "Pirc Defense": family({
    overview: "Die Pirc-Verteidigung erlaubt Weiß ein breites Zentrum und bereitet einen späteren Angriff darauf vor.",
    pawnStructures: ["Weiße Zentralbauern gewinnen Raum und können vorrücken, werden dadurch aber auch Ziele.", "Der schwarze Königsfianchetto richtet sich gegen das Zentrum."],
    development: ["Schwarz rochiert meist früh und entwickelt den Damenspringer flexibel.", "Weiß entwickelt hinter dem Zentrum und wählt zwischen ruhigem Raumspiel und Königsangriff."],
    whitePlans: ["Das Zentrum stabilisieren und Raum in Aktivität umwandeln.", "Schwarze Bauernhebel rechtzeitig kontrollieren."],
    blackPlans: ["Das weiße Zentrum mit Figuren und Bauernhebeln angreifen.", "Gegenspiel am Damenflügel oder gegen die Zentrumsspitze erzeugen."],
    commonMistakes: ["Als Weiß das Zentrum zu weit vorschieben und ungeschützt lassen.", "Als Schwarz nur fianchettieren und den notwendigen Zentrumskampf auslassen."],
    explanations: ["Schwarz überlässt Weiß Raum, um später klare Angriffsziele zu erhalten.", "Der fianchettierte Läufer macht Druck auf die lange Diagonale und unterstützt den Gegenangriff."],
  }),
  "Tarrasch Defense": family({
    overview: "Die Tarrasch-Verteidigung setzt auf aktive Figuren und ein freies Spiel, auch wenn Schwarz einen isolierten Zentralbauern akzeptiert.",
    pawnStructures: ["Ein isolierter Damenbauer gibt Raum und offene Linien, kann im Endspiel aber schwach werden.", "Der Kampf dreht sich oft um das Feld vor dem isolierten Bauern."],
    development: ["Schwarz entwickelt frei und nutzt offene Linien für Aktivität.", "Weiß blockiert den isolierten Bauern und tauscht aktive schwarze Figuren."],
    whitePlans: ["Den isolierten Bauern blockieren und langfristig angreifen.", "Schwarze Aktivität neutralisieren, bevor vereinfacht wird."],
    blackPlans: ["Aktive Figuren und mögliche Zentrumsvorstöße nutzen.", "Einen Königsangriff oder taktisches Spiel beginnen, bevor der Bauer zum Endspielziel wird."],
    commonMistakes: ["Als Weiß nur den Bauern belagern und schwarze Aktivität unterschätzen.", "Als Schwarz passiv in ein Endspiel mit schwachem Isolani gehen."],
    explanations: ["Schwarz tauscht strukturelle Perfektion gegen freie Entwicklung.", "Der isolierte Bauer kann zugleich Schwäche und Quelle aktiven Spiels sein."],
  }),
  "London System": family({
    overview: "Das Londoner System baut eine feste Entwicklungsschablone auf, deren Erfolg dennoch vom richtigen Zentrumsspiel abhängt.",
    pawnStructures: ["Ein weißes Bauerndreieck stützt das Zentrum und gibt dem Damenläufer außerhalb der Kette ein aktives Feld.", "Die Stellung ist solide, kann aber ohne Bauernhebel passiv werden."],
    development: ["Weiß entwickelt den Damenläufer vor dem Schließen der Bauernkette und rochiert meist kurz.", "Schwarz greift das weiße Zentrum an, statt den Aufbau nur zu spiegeln."],
    whitePlans: ["Den Königsflügel kontrolliert angreifen oder im Zentrum Raum gewinnen.", "Den schlecht platzierten Königsläufer verbessern."],
    blackPlans: ["Die weiße Bauernkette an ihrer Basis angreifen.", "Am Damenflügel Raum gewinnen und den weißen Standardaufbau stören."],
    commonMistakes: ["Die gleichen Züge unabhängig von der gegnerischen Aufstellung spielen.", "Einen Königsangriff beginnen, ohne das Zentrum zu beachten."],
    explanations: ["Der Damenläufer wird aktiviert, bevor der e-Bauer seine natürliche Diagonale schließt.", "Der Aufbau ist leicht zu lernen, verlangt aber trotzdem eine Reaktion auf gegnerische Bauernhebel."],
  }),
  "Colle System": family({
    overview: "Das Colle-System baut ein festes weißes Zentrum auf und bereitet eine spätere Öffnung für die Figuren vor.",
    pawnStructures: ["Das weiße Bauerndreieck ist stabil, schränkt aber zunächst den Damenläufer ein.", "Der zentrale Bauernhebel entscheidet, ob der Aufbau aktiv wird."],
    development: ["Weiß entwickelt sicher, rochiert und sammelt Kräfte hinter dem Zentrum.", "Schwarz nutzt den Raum, bevor Weiß das Zentrum öffnet."],
    whitePlans: ["Den zentralen Durchbruch sorgfältig vorbereiten.", "Nach der Öffnung Linien gegen den schwarzen König nutzen."],
    blackPlans: ["Den weißen Durchbruch kontrollieren und am Damenflügel Raum gewinnen.", "Den eingeschränkten weißen Damenläufer ausnutzen."],
    commonMistakes: ["Den zentralen Bauernhebel spielen, bevor alle Figuren bereitstehen.", "Die feste Aufstellung ohne aktiven Durchbruch weiterführen."],
    explanations: ["Die Bauernstruktur schafft Sicherheit und sammelt Kräfte für eine spätere Zentrumseröffnung.", "Der zunächst passive Damenläufer wird erst nach dem zentralen Durchbruch aktiv."],
  }),
  "Trompowsky Attack": family({
    overview: "Der Trompowsky-Angriff entwickelt den Damenläufer aktiv und stellt Schwarz früh vor eine konkrete strukturelle Entscheidung.",
    pawnStructures: ["Ein Läufertausch kann schwarze Doppelbauern erzeugen, gibt dafür aber das Läuferpaar ab.", "Weiß kann ein breites Zentrum aufbauen, während Schwarz die frühe Läuferstellung angreift."],
    development: ["Weiß muss nach dem frühen Läuferzug die übrigen Figuren zügig entwickeln.", "Schwarz entscheidet zwischen Strukturveränderung, Läuferjagd und ruhigem Zentrum."],
    whitePlans: ["Mögliche Strukturschwächen angreifen und Raum im Zentrum gewinnen.", "Den frühen Läuferzug durch schnelle weitere Entwicklung rechtfertigen."],
    blackPlans: ["Das Läuferpaar oder Entwicklungstempi gegen den Läufer nutzen.", "Das weiße Zentrum direkt bestreiten."],
    commonMistakes: ["Als Weiß den Läufer mehrfach ohne Gewinn bewegen.", "Als Schwarz Doppelbauern automatisch als dauerhaften Nachteil betrachten."],
    explanations: ["Der Läufer bindet oder tauscht einen wichtigen schwarzen Verteidiger des Zentrums.", "Die Eröffnung weicht Hauptvarianten aus, ohne auf Entwicklung zu verzichten."],
  }),
  "King's Indian Attack": family({
    overview: "Der Königsindische Angriff ist ein flexibler weißer Aufbau mit Fianchetto und einem späteren Vorstoß im Zentrum oder am Königsflügel.",
    pawnStructures: ["Weiße Bauern stützen eine geschlossene Kette, die Raum am Königsflügel ermöglichen kann.", "Schwarz erhält häufig Raum am Damenflügel und im Zentrum."],
    development: ["Weiß fianchettiert den Königsläufer, rochiert und entwickelt hinter der Bauernkette.", "Schwarz nutzt den freien Aufbau für aktive Zentrumskontrolle."],
    whitePlans: ["Das Zentrum schließen und am Königsflügel angreifen, wenn die Struktur dazu passt.", "Den fianchettierten Läufer nach einer Zentrumseröffnung aktivieren."],
    blackPlans: ["Am Damenflügel und gegen die weiße Bauernbasis spielen.", "Den weißen Königsangriff durch aktives Zentrumsspiel bremsen."],
    commonMistakes: ["Den Aufbau automatisch spielen, obwohl das Zentrum einen anderen Plan verlangt.", "Am Königsflügel angreifen, bevor die Bauernkette die Richtung vorgibt."],
    explanations: ["Das Fianchetto schafft eine sichere Königsstellung und langfristigen Druck auf der Diagonale.", "Der Aufbau ist ein System, aber der richtige Bauernhebel hängt von der gegnerischen Stellung ab."],
  }),
});

function copyList(value) {
  return Array.isArray(value) ? value.slice(0, 4) : [];
}

export function openingKnowledgeForFamily(familyName) {
  const specific = typeof familyName === "string"
    ? OPENING_FAMILY_KNOWLEDGE[familyName]
    : null;
  const knowledge = specific || generalKnowledge;
  return {
    version: 1,
    source: OPENING_KNOWLEDGE_SOURCE,
    scope: specific ? "family" : "general",
    family: specific ? familyName : null,
    overview: knowledge.overview,
    pawnStructures: copyList(knowledge.pawnStructures),
    development: copyList(knowledge.development),
    whitePlans: copyList(knowledge.whitePlans),
    blackPlans: copyList(knowledge.blackPlans),
    commonMistakes: copyList(knowledge.commonMistakes),
    explanations: copyList(knowledge.explanations),
  };
}

export function hasOpeningKnowledge(value) {
  return Boolean(
    value
    && value.source === OPENING_KNOWLEDGE_SOURCE
    && value.version === 1
    && typeof value.overview === "string"
    && value.overview.length > 0
  );
}
