import { parseTrainingExercise, validateTrainingExercise } from "./trainingValidation.js";

const curated = ({
  id,
  fen,
  bestMoveUci,
  acceptableMoves = [bestMoveUci],
  continuation = [],
  concept,
  concepts = [concept],
  category = "tactical",
  difficulty = "beginner",
  short,
  detailed,
  takeaway,
  hints,
  reference = "curated-mvp",
  stockfishBestMoves = [bestMoveUci],
}) => ({
  id,
  fen,
  sideToMove: fen.split(" ")[1] === "b" ? "black" : "white",
  type: "best_move",
  category,
  solution: { bestMoveUci, acceptableMoves, continuation },
  concepts,
  primaryConcept: concept,
  difficulty,
  explanation: { short, detailed, takeaway },
  hints,
  source: { type: "curated", gameId: null, ply: null, reference },
  metadata: {
    validation: {
      legalMoveChecked: true,
      continuationChecked: true,
      stockfishBestMoves,
    },
  },
});

const RAW_CURATED_EXERCISES = [
  curated({
    id: "training_fork_01",
    fen: "4k3/5q2/8/5N2/8/8/8/K7 w - - 0 1",
    bestMoveUci: "f5d6",
    continuation: ["e8f8", "d6f7"],
    concept: "tactics.fork",
    short: "Nd6+ greift König und Dame gleichzeitig an.",
    detailed: "Der Springer zieht mit Schach nach d6 und attackiert zugleich die Dame auf f7. Schwarz muss zuerst den König retten; danach gewinnt Nxf7 die Dame.",
    takeaway: "Suche nach Springerfeldern, die Schach geben und gleichzeitig ein wertvolles zweites Ziel angreifen.",
    hints: ["Beginne mit allen Schachs.", "Welches Springerfeld greift e8 und f7 zugleich an?", "Der Springer möchte nach d6."],
  }),
  curated({
    id: "training_fork_02",
    fen: "6k1/8/8/1b6/8/8/8/K2Q4 w - - 0 1",
    bestMoveUci: "d1d5",
    continuation: ["g8f8", "d5b5"],
    concept: "tactics.fork",
    short: "Qd5+ verbindet Schach mit einem Angriff auf den Läufer.",
    detailed: "Von d5 aus gibt die Dame dem König auf g8 Schach und greift gleichzeitig den Läufer auf b5 an. Nach der erzwungenen Königantwort fällt der Läufer.",
    takeaway: "Damengabeln sind besonders stark, wenn eines der Ziele der König ist.",
    hints: ["Suche einen forcierenden Damenzug.", "Kann die Dame König und Läufer auf einer Linie treffen?", "Das gemeinsame Angriffsfeld ist d5."],
  }),
  curated({
    id: "training_fork_03",
    fen: "6k1/p1p1P1p1/3N2Kp/2R2P2/6Q1/1P1q2P1/P6r/8 b - - 0 40",
    bestMoveUci: "d3d6",
    continuation: ["f5f6", "d6f6"],
    concept: "tactics.fork",
    difficulty: "intermediate",
    short: "...Qd6+ gabelt König und Turm.",
    detailed: "Die Dame gibt auf d6 Schach auf der sechsten Reihe und greift zugleich den Turm c5 an. Nach f6 wird die Stellung sogar mit ...Qxf6# entschieden.",
    takeaway: "Ein Damenschach mit zweitem Angriffsziel kann zugleich Materialgewinn und Mattdrohung verbinden.",
    hints: ["Beginne mit allen Damenschachs.", "Welches Schach greift zugleich den Turm c5 an?", "Die Dame gehört nach d6."],
    reference: "lichess-puzzle-QIWbI",
  }),
  curated({
    id: "training_fork_04",
    fen: "r1bq1rk1/pp3p1p/2p2p2/2bP1N2/2n5/4N3/PPP2PPP/R2QK2R w KQ - 0 13",
    bestMoveUci: "d1g4",
    continuation: ["g8h8", "g4g7"],
    concept: "tactics.fork",
    difficulty: "intermediate",
    short: "Qg4 verbindet ein langes Schach mit der Mattdrohung auf g7.",
    detailed: "Die Dame nutzt die offene g-Linie für Qg4+. Der König muss nach h8, danach schlägt Qxg7# den Bauern und beendet die Partie; der Schachzug trifft mehrere Ziele zugleich.",
    takeaway: "Ein Doppelangriff kann statt Materialgewinn eine zweite, unmittelbare Mattdrohung erzeugen.",
    hints: ["Suche ein Damenschach auf einer offenen Linie.", "Die schwarze g-Linie führt direkt zum König.", "Qg4+ erzwingt ...Kh8."],
    reference: "lichess-puzzle-8nRw2",
  }),
  curated({
    id: "training_fork_05",
    fen: "rn2k2r/p3p1bp/1p2P1p1/1Np2bp1/2P5/5P2/PP4PP/3RKB1R w Kkq - 2 15",
    bestMoveUci: "b5c7",
    continuation: ["e8f8", "d1d8"],
    concept: "tactics.fork",
    difficulty: "intermediate",
    short: "Nc7+ gabelt König und Turm und bereitet das Matt vor.",
    detailed: "Der Springer springt mit Schach nach c7 und greift gleichzeitig den Turm a8 an. Nach ...Kf8 ist jedoch Rd8# noch stärker als der reine Materialgewinn.",
    takeaway: "Eine Gabel kann eine zusätzliche Mattidee ermöglichen; prüfe nach der Königantwort immer weiter forcierte Züge.",
    hints: ["Suche ein Springerschach.", "Welches Feld greift e8 und a8 zugleich an?", "Nc7+ ist der Doppelangriff."],
    reference: "lichess-puzzle-cs0KE",
  }),

  curated({
    id: "training_pin_01",
    fen: "r3k1nr/1pp2ppp/1pq5/n3p3/Q1B5/2P5/PP3PPP/R1B2RK1 w kq - 2 15",
    bestMoveUci: "c4b5",
    continuation: ["c6b5", "a4b5"],
    concept: "tactics.pin",
    difficulty: "intermediate",
    short: "Bb5 nutzt die Fesselung der Dame vor dem König.",
    detailed: "Mit Bb5 richtet Weiß Läufer, schwarze Dame und König auf derselben Diagonale aus. Nach ...Qxb5 kann die weiße Dame mit Qxb5+ zurückschlagen und die schwarze Dame gewinnen.",
    takeaway: "Eine Figur vor dem König kann trotz eines legalen Schlagzugs taktisch gebunden sein, weil die Linie danach offen bleibt.",
    hints: ["Betrachte die Diagonale zum König e8.", "Der Läufer kann die schwarze Dame auf diese Linie zwingen.", "Spiele Bb5."],
    reference: "lichess-puzzle-ncss0",
  }),
  curated({
    id: "training_pin_02",
    fen: "5r1k/2p3p1/p4B1p/2P5/1P2PQP1/P7/6KP/3q4 w - - 3 37",
    bestMoveUci: "f4h6",
    continuation: ["h8g8", "h6g7"],
    concept: "tactics.pin",
    difficulty: "intermediate",
    short: "Qh6+ nutzt den absolut gefesselten g-Bauern.",
    detailed: "Der Läufer f6 fesselt den Bauern g7 an den König h8. Deshalb kann der Bauer die Dame auf h6 nicht schlagen; nach ...Kg8 folgt Qg7#.",
    takeaway: "Eine absolut gefesselte Figur darf selbst dann nicht ziehen, wenn sie die angreifende Dame schlagen könnte.",
    hints: ["Der Bauer g7 steht vor seinem König auf der Läuferdiagonale.", "Nutze die Fesselung mit einem Damenschach.", "Qh6+ bereitet Qg7# vor."],
    reference: "lichess-puzzle-fAwGP",
  }),
  curated({
    id: "training_pin_03",
    fen: "r4bnr/pp3kp1/4p3/3qn1Bp/3Q3P/2P5/PP3P2/2KR2N1 w - - 1 18",
    bestMoveUci: "d4f4",
    continuation: ["g8f6", "d1d5", "e6d5"],
    concept: "tactics.pin",
    difficulty: "advanced",
    short: "Qf4+ erzwingt eine blockierende und gefesselte Figur.",
    detailed: "Qf4+ gibt Schach auf der f-Linie. ...Nf6 muss die Linie schließen; der Springer ist danach an den König gebunden, sodass Rxd5! taktisch möglich wird.",
    takeaway: "Eine Fesselung kann durch einen forcierenden Zug erst geschaffen werden und anschließend einen anderen Verteidiger ausschalten.",
    hints: ["Suche ein Damenschach auf einer offenen Linie.", "Welche Antwort muss die f-Linie schließen?", "Qf4+ erzwingt ...Nf6."],
    reference: "lichess-puzzle-c5HpM",
  }),
  curated({
    id: "training_pin_04",
    fen: "8/5kp1/4p2p/1pBr4/1P2N3/3q3P/4QPP1/5K2 b - - 5 37",
    bestMoveUci: "d3b1",
    continuation: ["e2e1", "d5d1"],
    concept: "tactics.pin",
    difficulty: "advanced",
    short: "...Qb1+ zwingt die Dame in eine tödliche Fesselung.",
    detailed: "Nach ...Qb1+ muss Qe1 das Schach abfangen. ...Rd1 stellt den Turm neben die weiße Dame; sie ist nun vor dem König f1 gebunden und kann die Stellung nicht mehr halten.",
    takeaway: "Mit einem Schach kann man einen Verteidiger auf ein Feld zwingen, auf dem er anschließend gefesselt wird.",
    hints: ["Beginne mit einem Damenschach.", "Zwinge die weiße Dame vor den eigenen König.", "...Qb1+ leitet die Fesselung ein."],
    reference: "lichess-puzzle-P3fTj",
  }),

  curated({
    id: "training_loose_01",
    fen: "3q3k/8/8/8/8/8/8/K2Q4 w - - 0 1",
    bestMoveUci: "d1d8",
    concept: "tactics.loose-piece",
    short: "Die schwarze Dame hängt auf der offenen d-Linie.",
    detailed: "Zwischen den Damen steht keine Figur. Qxd8+ gewinnt die ungedeckte schwarze Dame sofort und geschieht sogar mit Schach.",
    takeaway: "Scanne nach jedem Zug alle ungedeckten Figuren und offenen Linien.",
    hints: ["Welche schwarze Figur ist ungedeckt?", "Prüfe die vollständig offene d-Linie.", "Die weiße Dame kann direkt auf d8 schlagen."],
  }),
  curated({
    id: "training_loose_02",
    fen: "r6k/8/8/8/8/8/8/R6K w - - 0 1",
    bestMoveUci: "a1a8",
    concept: "tactics.loose-piece",
    short: "Rxa8+ gewinnt den losen Turm.",
    detailed: "Die a-Linie ist frei und der schwarze Turm ist nicht gedeckt. Weiß schlägt ihn mit Schach und entscheidet den Materialkampf sofort.",
    takeaway: "Eine offene Linie ist eine direkte Verbindung: Prüfe immer, was am anderen Ende ungedeckt steht.",
    hints: ["Die Türme sehen sich auf derselben Linie.", "Der schwarze Turm hat keinen Verteidiger.", "Spiele Rxa8+."],
  }),
  curated({
    id: "training_loose_03",
    fen: "7k/8/8/2b5/8/8/8/K5Q1 b - - 0 1",
    bestMoveUci: "c5g1",
    concept: "tactics.loose-piece",
    short: "...Bxg1 gewinnt die ungeschützte Dame.",
    detailed: "Die lange Diagonale c5–g1 ist vollständig offen. Der Läufer kann die weiße Dame ohne taktischen Nachteil schlagen.",
    takeaway: "Vor dem eigenen Zug und nach jedem gegnerischen Zug lohnt sich ein Blick entlang aller Läuferdiagonalen.",
    hints: ["Folge der Diagonale des Läufers.", "Auf g1 steht das wertvollste Ziel.", "Der Läufer kann Bxg1 spielen."],
  }),

  curated({
    id: "training_mate_01",
    fen: "6k1/5ppp/8/8/8/8/8/K3R3 w - - 0 1",
    bestMoveUci: "e1e8",
    concept: "tactics.back-rank-tactic",
    concepts: ["tactics.back-rank-tactic", "checkmate.mating-net"],
    short: "Re8# nutzt die eingeschlossene Grundreihe.",
    detailed: "Der Turm dringt auf e8 ein. Die schwarzen Bauern versperren dem König alle Fluchtfelder auf der siebten Reihe; auf der achten Reihe kontrolliert der Turm jedes Feld.",
    takeaway: "Ein König ohne Luftloch ist auf einer offenen Grundreihe ständig mattgefährdet.",
    hints: ["Der schwarze König hat kein Fluchtfeld.", "Suche ein Turmschach auf der achten Reihe.", "Re8 ist sofort matt."],
  }),
  curated({
    id: "training_mate_02",
    fen: "7k/8/5K2/8/6Q1/8/8/8 w - - 0 1",
    bestMoveUci: "g4g7",
    concept: "checkmate.mating-net",
    short: "Qg7# schließt den König in der Ecke ein.",
    detailed: "Die Dame gibt auf g7 Schach und kontrolliert g8 sowie h7. Der weiße König auf f6 schützt die Dame, sodass der schwarze König sie nicht schlagen kann.",
    takeaway: "Dame und König bilden im Endspiel ein Mattnetz, wenn die Dame gedeckt alle Fluchtfelder nimmt.",
    hints: ["Die Dame braucht Unterstützung durch den eigenen König.", "Welches Feld neben h8 kontrolliert g8 und h7?", "Qg7 ist matt."],
  }),
  curated({
    id: "training_mate_03",
    fen: "6rk/6pp/8/4N3/8/8/8/K7 w - - 0 1",
    bestMoveUci: "e5f7",
    concept: "checkmate.mating-net",
    difficulty: "intermediate",
    short: "Nf7# ist ein ersticktes Matt.",
    detailed: "Der Springer gibt dem König auf h8 Schach. Die eigenen schwarzen Figuren und Bauern blockieren jedes Fluchtfeld; ein Springerschach kann zudem nicht durch eine Zwischenfigur geblockt werden.",
    takeaway: "Ein eingesperrter König ist besonders anfällig für Springerschachs.",
    hints: ["Der König ist von eigenen Steinen eingeschlossen.", "Springerschachs lassen sich nicht blocken.", "Der Springer kann nach f7."],
  }),

  curated({
    id: "training_discovery_01",
    fen: "1q2k3/8/8/4N3/8/8/8/K3R3 w - - 0 1",
    bestMoveUci: "e5c6",
    continuation: ["e8d7", "c6b8"],
    concept: "tactics.discovered-attack",
    difficulty: "intermediate",
    short: "Nc6+ öffnet die e-Linie und greift die Dame an.",
    detailed: "Der Springer verlässt die e-Linie und deckt dadurch das Turmschach auf den König auf. Gleichzeitig attackiert er von c6 die Dame b8.",
    takeaway: "Bei einer Batterie sollte die vordere Figur mit möglichst großem eigenem Tempo abziehen.",
    hints: ["Der Springer blockiert den eigenen Turm.", "Finde einen Abzug, der selbst die Dame angreift.", "Nc6+ erfüllt beide Aufgaben."],
  }),
  curated({
    id: "training_discovery_02",
    fen: "8/7k/8/7q/8/3N4/8/KB6 w - - 0 1",
    bestMoveUci: "d3f4",
    continuation: ["h7g8", "f4h5"],
    concept: "tactics.discovered-attack",
    difficulty: "intermediate",
    short: "Nf4+ deckt ein Läuferschach auf und greift die Dame an.",
    detailed: "Der Springer räumt die lange Diagonale b1–h7 für den Läufer. Auf f4 greift er zusätzlich die Dame h5 an, die nach der Königantwort verloren geht.",
    takeaway: "Die stärksten Abzugsangriffe verbinden die geöffnete Linie mit einer zweiten Drohung der abziehenden Figur.",
    hints: ["Öffne die Diagonale des Läufers.", "Der Springer soll zugleich die Dame h5 angreifen.", "Das richtige Abzugsfeld ist f4."],
  }),
  curated({
    id: "training_discovery_03",
    fen: "1q6/8/8/8/R2B3k/8/8/K7 w - - 0 1",
    bestMoveUci: "d4e5",
    acceptableMoves: ["d4e5", "d4a7"],
    continuation: ["h4g5", "e5b8"],
    concept: "tactics.discovered-attack",
    difficulty: "advanced",
    short: "Be5+ öffnet das Turmschach und greift die Dame an.",
    detailed: "Der Läufer verlässt die vierte Reihe, sodass der Turm auf a4 den König h4 angreift. Von e5 aus zielt er zugleich auf die Dame b8; Ba7+ ist hier eine gleichwertige Abzugsalternative.",
    takeaway: "Ein Abzugsschach verschafft der abziehenden Figur Zeit für einen zweiten Angriff.",
    hints: ["Der Läufer blockiert die Wirkung des Turms.", "Auf welchem Abzugsfeld greift der Läufer b8 an?", "Be5+ öffnet die Reihe."],
  }),

  curated({
    id: "training_defender_01",
    fen: "rk6/1r3ppp/3R4/pp1p4/2pP4/2P1P3/5PPP/R4K2 w - - 0 24",
    bestMoveUci: "d6d8",
    continuation: ["b8c7", "d8a8"],
    concept: "tactics.deflection",
    difficulty: "intermediate",
    short: "Rxd8 lenkt den König vom Turm a8 ab.",
    detailed: "Mit Rxd8+ zwingt Weiß den König nach c7. Erst dadurch ist der Turm a8 nicht mehr vom König geschützt, und Rxa8 gewinnt den zweiten Turm.",
    takeaway: "Frage bei jedem Verteidiger, welches Ziel nach einem erzwungenen Wegzug ungedeckt wäre.",
    hints: ["Beginne mit einem Schach auf der achten Reihe.", "Der König verteidigt den Turm a8.", "Rxd8+ lenkt den König ab."],
    reference: "lichess-puzzle-2358546e4c2a8b4d",
    stockfishBestMoves: ["d6d8"],
  }),
  curated({
    id: "training_defender_02",
    fen: "8/pp1r2k1/7p/8/3q1p2/P1QNpP2/1P4KP/4R3 b - - 3 35",
    bestMoveUci: "d4c3",
    continuation: ["b2c3", "d7d3"],
    concept: "tactics.removing-the-defender",
    difficulty: "intermediate",
    short: "...Qxc3 entfernt den Bauern, der d3 kontrolliert.",
    detailed: "Die Dame schlägt auf c3 mit Tempo. Nach bxc3 kann der Turm auf d3 eindringen; der b-Bauer wurde von seiner Verteidigungsaufgabe abgelenkt und die dritte Reihe öffnet sich.",
    takeaway: "Ein Verteidiger kann durch einen Schlagabtausch von seinem wichtigen Feld entfernt werden.",
    hints: ["Welche weiße Figur hält den schwarzen Turm aus d3 heraus?", "Suche einen Damenabtausch mit Ablenkung.", "...Qxc3! bereitet ...Rd3 vor."],
    reference: "lichess-puzzle-a301d5eaa8df1d28",
    stockfishBestMoves: ["d4c3"],
  }),
  curated({
    id: "training_defender_03",
    fen: "4r2k/p1bR4/2p5/2Pp1Np1/2bP4/2N4P/P1B2PP1/6K1 b - - 0 27",
    bestMoveUci: "e8e1",
    concept: "tactics.removing-the-defender",
    difficulty: "intermediate",
    short: "...Re1# nutzt die überlastete erste Reihe.",
    detailed: "Der Turm dringt nach e1 ein. Die weißen Figuren können die Grundreihe und den König nicht gleichzeitig sichern; der entscheidende Verteidiger fehlt auf e1.",
    takeaway: "Wenn mehrere Figuren dieselbe Verteidigungsaufgabe teilen müssen, prüfe zuerst forcierte Eindringzüge.",
    hints: ["Suche ein Turmschach auf der ersten Reihe.", "Der weiße König hat kaum Fluchtfelder.", "...Re1 entscheidet sofort."],
    reference: "lichess-puzzle-d4fb023dfd41ff04",
    stockfishBestMoves: ["e8e1"],
  }),

  curated({
    id: "training_passed_01",
    fen: "5k2/3K4/6pp/8/8/4P3/8/8 w - - 0 61",
    bestMoveUci: "e3e4",
    continuation: ["h6h5", "e4e5"],
    concept: "pawns.passed-pawn",
    category: "endgame",
    short: "e4 setzt den entfernten Freibauern sofort in Bewegung.",
    detailed: "Der weiße König bindet den schwarzen König, während der e-Bauer freie Bahn hat. Mit e4 beginnt das entscheidende Bauernrennen ohne ein Tempo zu verlieren.",
    takeaway: "Ein entfernter Freibauer ist nur stark, wenn er rechtzeitig aktiviert wird.",
    hints: ["Welcher Bauer hat freie Bahn zur Umwandlung?", "Im Bauernrennen zählt jedes Tempo.", "Beginne mit e4."],
    reference: "lichess-puzzle-663f75430d5e5e7d",
    stockfishBestMoves: ["e3e4"],
  }),
  curated({
    id: "training_passed_02",
    fen: "8/8/8/p6p/2P5/3K4/P5k1/8 w - - 1 47",
    bestMoveUci: "c4c5",
    continuation: ["h5h4", "c5c6"],
    concept: "pawns.passed-pawn",
    category: "endgame",
    difficulty: "intermediate",
    short: "c5 schafft das nötige Tempo im Bauernrennen.",
    detailed: "Weiß darf den schwarzen h-Bauern nicht nur mit dem König verfolgen. Der eigene c-Freibauer wird sofort vorgeschoben und erzeugt eine ebenso konkrete Umwandlungsdrohung.",
    takeaway: "Gegen einen entfernten Freibauern ist aktives Gegenspiel oft stärker als passives Hinterherlaufen.",
    hints: ["Beide Seiten besitzen einen entfernten Freibauern.", "Suche aktives Gegenspiel statt passiver Verteidigung.", "Schiebe den c-Bauern nach c5."],
    reference: "lichess-puzzle-c068f8cfe1073998",
    stockfishBestMoves: ["c4c5"],
  }),

  curated({
    id: "training_king_01",
    fen: "8/8/8/5K1p/7P/6k1/8/8 w - - 1 54",
    bestMoveUci: "f5g5",
    continuation: ["g3f3", "g5h5"],
    concept: "endgame.active-king",
    category: "endgame",
    short: "Kg5 bringt den König vor den Freibauern.",
    detailed: "Der König übernimmt selbst die wichtigste Aufgabe: Er nähert sich h5, schützt den eigenen Bauern und hält den schwarzen König vom Umwandlungsweg fern.",
    takeaway: "Im Endspiel ist der König eine aktive Figur und gehört zu den entscheidenden Bauern.",
    hints: ["Der König muss den eigenen Bauern unterstützen.", "Suche den kürzesten Weg nach h5.", "Kg5 aktiviert den König."],
    reference: "lichess-puzzle-119f756f99ebd6cb",
    stockfishBestMoves: ["f5g5"],
  }),
  curated({
    id: "training_king_02",
    fen: "8/5k2/2K3p1/6P1/5P2/8/8/8 b - - 2 66",
    bestMoveUci: "f7e6",
    continuation: ["c6c5", "e6f5"],
    concept: "endgame.active-king",
    category: "endgame",
    difficulty: "intermediate",
    short: "...Ke6 zentralisiert den König rechtzeitig.",
    detailed: "Der schwarze König geht nach e6 und hält den weißen König von den Bauern fern. Nach Kc5 folgt ...Kf5, wodurch Schwarz die wichtigen Schlüsselfelder erreicht.",
    takeaway: "Königsaktivität bedeutet, den gegnerischen König abzuschneiden und Schlüsselfelder zuerst zu besetzen.",
    hints: ["Schwarz muss den gegnerischen König begrenzen.", "Welches zentrale Feld erreicht beide weißen Bauern?", "...Ke6 ist der präzise Weg."],
    reference: "lichess-puzzle-5901de69e93689d8",
    stockfishBestMoves: ["f7e6"],
  }),

  curated({
    id: "training_defence_01",
    fen: "8/4kppp/P3p3/r5P1/7P/8/3R4/K7 w - - 2 39",
    bestMoveUci: "d2a2",
    continuation: ["a5a2", "a1a2"],
    concept: "defence.active-defence",
    category: "positional",
    difficulty: "intermediate",
    short: "Ra2 erzwingt den Turmtausch und beseitigt das Gegenspiel.",
    detailed: "Weiß stellt den Turm aktiv hinter den gefährlichen a-Bauern. Nach ...Rxa2+ kann der König zurückschlagen; das Turmendspiel wird in ein übersichtliches Bauernendspiel überführt.",
    takeaway: "Aktive Verteidigung sucht einen konkreten Abtausch oder Gegenangriff statt passiv zu warten.",
    hints: ["Der schwarze Turm und der a-Bauer sind die Gefahren.", "Kann Weiß einen Turmtausch erzwingen?", "Ra2 stellt sich aktiv in die Linie."],
    reference: "lichess-puzzle-38e964492b7fcd12",
    stockfishBestMoves: ["d2a2"],
  }),
  curated({
    id: "training_defence_02",
    fen: "8/8/5p2/8/8/2K1k3/1P6/8 b - - 1 57",
    bestMoveUci: "f6f5",
    continuation: ["c3c2", "f5f4"],
    concept: "defence.active-defence",
    category: "positional",
    difficulty: "intermediate",
    short: "...f5 schafft sofortiges Gegenspiel am anderen Flügel.",
    detailed: "Schwarz kann den b-Bauern nicht passiv aufhalten. Mit ...f5 und ...f4 entsteht ein eigener Freibauer, der den weißen König zu einer schwierigen Entscheidung zwingt.",
    takeaway: "In schlechteren Endspielen ist ein eigener entfernter Freibauer oft die beste Verteidigungsressource.",
    hints: ["Passives Warten verliert gegen den b-Bauern.", "Schwarz braucht eine eigene konkrete Drohung.", "Starte mit ...f5."],
    reference: "lichess-puzzle-65cd0aa9aa9d6cca",
    stockfishBestMoves: ["f6f5"],
  }),
];

export function validateCuratedExerciseSet(rawExercises = RAW_CURATED_EXERCISES) {
  const errors = [];
  const ids = new Set();
  for (const input of rawExercises) {
    if (ids.has(input.id)) errors.push(`Doppelte Exercise-ID: ${input.id}.`);
    ids.add(input.id);
    const validation = validateTrainingExercise(input);
    for (const error of validation.errors) errors.push(`${input.id}: ${error}`);
  }
  return { valid: errors.length === 0, errors, count: rawExercises.length };
}

const setValidation = validateCuratedExerciseSet();
if (!setValidation.valid) {
  throw new Error(`Ungültiger Trainingsdatensatz:\n${setValidation.errors.join("\n")}`);
}

export const CURATED_TRAINING_EXERCISES = Object.freeze(
  RAW_CURATED_EXERCISES.map(parseTrainingExercise),
);

export function trainingExerciseById(id) {
  return CURATED_TRAINING_EXERCISES.find((exercise) => exercise.id === id) || null;
}
