import { deepFreeze } from "./freeze.js";
import { KNOWLEDGE_SCHEMA_VERSION } from "./taxonomy.js";

const card = ({
  id,
  en,
  de,
  categories,
  difficulty = ["beginner", "intermediate"],
  aliases = [],
  definition,
  explanation,
  cues,
  recommendations,
  exceptions,
  mistakes,
  questions,
  training,
  related = [],
  signals = [],
  keywords,
  phases = ["all"],
}) => ({
  id,
  version: KNOWLEDGE_SCHEMA_VERSION,
  name: { en, de },
  categories,
  difficulty,
  aliases: { de: aliases },
  definition: { de: definition },
  explanation: { de: explanation },
  recognitionCues: { de: cues },
  recommendations: { de: recommendations },
  exceptions: { de: exceptions },
  commonMistakes: { de: mistakes },
  practicalQuestions: { de: questions },
  training: { de: training },
  relatedConcepts: related,
  retrieval: {
    signals,
    keywords: { de: keywords },
    phases,
  },
  source: {
    type: "curated",
    note: "Kuratierte Originalzusammenfassung; konkrete Stellungsbehauptungen benötigen separate Brett- oder Engine-Evidenz.",
  },
});

export const CORE_CHESS_CONCEPTS = deepFreeze([
  card({
    id: "opening.rapid-development",
    en: "Rapid Development",
    de: "Schnelle Entwicklung",
    categories: ["opening", "piece-activity"],
    definition: "Schnelle Entwicklung bringt die Figuren mit möglichst wenigen sinnvollen Zügen auf aktive Felder.",
    explanation: "In der Eröffnung zählt jeder Zug. Wer mehr Figuren ins Spiel bringt, kontrolliert mehr Felder, kann früher rochieren und erhält häufiger die Initiative. Entwicklung ist dabei kein Selbstzweck: Die gewählten Felder sollen zur Stellung passen.",
    cues: ["Mehrere eigene Leichtfiguren stehen noch auf ihren Ausgangsfeldern.", "Der Gegner hat deutlich mehr aktive Figuren oder bereits rochiert."],
    recommendations: ["Entwickle möglichst mit Tempo oder Einfluss auf das Zentrum.", "Bevorzuge Züge, die gleichzeitig Entwicklung und Königssicherheit fördern."],
    exceptions: ["Eine konkrete taktische Drohung oder ein notwendiger Verteidigungszug kann Vorrang haben."],
    mistakes: ["Bauernzüge oder Randzüge ohne dringenden Zweck werden mit Entwicklung verwechselt."],
    questions: ["Welche unentwickelte Figur kann sofort sinnvoll mitspielen?", "Kann ich entwickeln und zugleich eine Drohung beantworten?"],
    training: "Markiere nach jeder eigenen Eröffnungspartie, wann beide Springer, beide Läufer und der König einsatzbereit waren.",
    related: ["opening.development-before-attack", "opening.repeated-piece-moves", "opening.castling"],
    signals: ["minor-pieces-on-starting-squares", "more-minor-pieces-on-starting-squares-than-opponent"],
    keywords: ["entwicklung", "figuren raus", "tempo", "eröffnung"],
    phases: ["opening"],
  }),
  card({
    id: "opening.development-before-attack",
    en: "Development before Attack",
    de: "Entwicklung vor Angriff",
    categories: ["opening", "attack", "decision-making"],
    definition: "Ein Angriff sollte gewöhnlich erst beginnen, wenn genügend Figuren entwickelt sind und ihn unterstützen können.",
    explanation: "Ein verfrühter Angriff wird oft nur von Dame und wenigen Figuren getragen. Der Gegner kann Drohungen mit natürlichen Entwicklungszügen abwehren und dabei Tempi gewinnen. Vollständige Entwicklung erhöht dagegen Kraft, Sicherheit und Auswahl des Angreifers.",
    cues: ["Ein früher Angriff bindet fast nur Dame und Bauern ein.", "Mehrere eigene Leichtfiguren und ein Turm sind noch nicht am Spiel beteiligt."],
    recommendations: ["Zähle vor dem Angriff die tatsächlich beteiligten Figuren beider Seiten.", "Verbessere zunächst Entwicklung oder Königssicherheit, wenn kein konkreter Gewinn vorhanden ist."],
    exceptions: ["Ein unmittelbar berechenbarer Materialgewinn oder Mattangriff darf allgemeine Eröffnungsprinzipien überstimmen."],
    mistakes: ["Ein einzelner Schachzug oder Damenangriff wird bereits als tragfähiger Angriff bewertet."],
    questions: ["Welche meiner Figuren können das Angriffsfeld erreichen?", "Kann der Gegner meine Drohung durch Entwicklung abwehren?"],
    training: "Untersuche kritische Eröffnungsstellungen ohne Engine und notiere zuerst Beteiligung, Entwicklung und Königssicherheit beider Seiten.",
    related: ["opening.rapid-development", "opening.early-queen-development", "strategy.initiative"],
    signals: ["minor-pieces-on-starting-squares", "more-minor-pieces-on-starting-squares-than-opponent"],
    keywords: ["zu früh angegriffen", "angriff", "entwicklung vor angriff", "unentwickelt"],
    phases: ["opening"],
  }),
  card({
    id: "opening.early-queen-development",
    en: "Early Queen Development",
    de: "Frühe Damenentwicklung",
    categories: ["opening", "piece-activity"],
    definition: "Eine früh entwickelte Dame kann zum Angriffsziel werden und dem Gegner Entwicklung mit Tempogewinn erlauben.",
    explanation: "Die Dame ist wertvoll und muss Angriffen meist ausweichen. Wird sie in der Eröffnung mehrfach vertrieben, entwickelt der Gegner seine Figuren kostenlos, während die übrigen eigenen Figuren zurückbleiben. Entscheidend ist nicht der frühe Damenzug allein, sondern seine konkrete Verwundbarkeit.",
    cues: ["Die Dame verlässt früh ihre Ausgangsstellung und kann von Leichtfiguren angegriffen werden.", "Aufeinanderfolgende Damenzüge kosten Zeit, während andere Figuren unentwickelt bleiben."],
    recommendations: ["Prüfe vor einem frühen Damenzug alle natürlichen Entwicklungszüge des Gegners mit Tempo.", "Nutze die Dame früh nur mit einem konkreten, tragfähigen Zweck."],
    exceptions: ["Ein früher Damenzug kann korrekt sein, wenn er Material gewinnt, eine konkrete Drohung löst oder nicht sinnvoll angegriffen werden kann."],
    mistakes: ["Jeder frühe Damenzug wird pauschal als Fehler behandelt, obwohl konkrete Taktik entscheidet."],
    questions: ["Wie kann der Gegner meine Dame entwickeln und zugleich angreifen?", "Muss meine Dame in den nächsten Zügen wahrscheinlich erneut ziehen?"],
    training: "Suche in eigenen Partien nach Damenbewegungen vor der Rochade und prüfe, wie viele davon durch gegnerische Angriffe erzwungen wurden.",
    related: ["opening.repeated-piece-moves", "opening.rapid-development", "opening.development-before-attack"],
    signals: ["early-queen-move-observed"],
    keywords: ["dame zu früh", "frühe dame", "damenentwicklung", "dame angegriffen"],
    phases: ["opening"],
  }),
  card({
    id: "opening.repeated-piece-moves",
    en: "Repeated Piece Moves",
    de: "Wiederholte Figurenzüge",
    categories: ["opening", "mistake-classification"],
    definition: "Mehrfache Züge derselben Figur können in der Eröffnung Entwicklungstempi kosten und andere Figuren zurücklassen.",
    explanation: "Jeder zusätzliche Zug mit einer bereits entwickelten Figur muss einen konkreten Mehrwert schaffen. Andernfalls nutzt der Gegner die Zeit, um weitere Kräfte zu aktivieren, das Zentrum zu besetzen oder den König zu sichern. Wiederholung ist ein Warnsignal, kein automatischer Fehler.",
    cues: ["Dieselbe Figur zieht mehrfach, bevor die übrigen Leichtfiguren entwickelt sind.", "Der Gegner gewinnt währenddessen einen sichtbaren Entwicklungsvorsprung."],
    recommendations: ["Vergleiche den Nutzen des zweiten Figurenzugs mit der Entwicklung einer neuen Figur.", "Vermeide Felder, auf denen eine Figur leicht mit Tempo vertrieben wird."],
    exceptions: ["Erzwungene Rückzüge, konkrete Taktik und starke Tempodrohungen rechtfertigen wiederholte Züge."],
    mistakes: ["Ein optisch aktiver Figurenzug wird wiederholt, obwohl er keine neue Drohung schafft."],
    questions: ["Was erreiche ich mit dem erneuten Zug konkret?", "Welche noch unentwickelte Figur könnte stattdessen verbessert werden?"],
    training: "Zähle in den ersten zehn eigenen Zügen jede Figurenbewegung und begründe schriftlich jede Wiederholung derselben Figur.",
    related: ["opening.rapid-development", "opening.early-queen-development", "strategy.improve-worst-piece"],
    signals: ["repeated-piece-move", "development-lag", "tempo-loss"],
    keywords: ["figur zweimal", "wiederholte züge", "tempo verloren", "mehrfach gezogen"],
    phases: ["opening"],
  }),
  card({
    id: "opening.fight-for-centre",
    en: "Fight for the Centre",
    de: "Kampf um das Zentrum",
    categories: ["opening", "strategy"],
    definition: "Der Kampf um das Zentrum soll zentrale Felder besetzen, kontrollieren oder den gegnerischen Einfluss dort untergraben.",
    explanation: "Zentrale Kontrolle gibt Figuren mehr Bewegungsmöglichkeiten und erleichtert den Wechsel zwischen beiden Flügeln. Das Zentrum kann mit Bauern besetzt, mit Figuren kontrolliert oder später durch einen Bauernhebel angegriffen werden. Keine dieser Methoden ist unabhängig von der konkreten Stellung richtig.",
    cues: ["Eine Seite erlaubt dem Gegner unangefochtene zentrale Bauernkontrolle.", "Eigene Figuren haben wegen fehlender Zentrumswirkung wenige aktive Felder."],
    recommendations: ["Prüfe bei jedem Eröffnungszug seine Wirkung auf die vier zentralen Felder.", "Greife ein großes gegnerisches Bauernzentrum rechtzeitig mit Figuren oder Bauernhebeln an."],
    exceptions: ["Hypermoderne Systeme überlassen dem Gegner vorübergehend Raum, um das Zentrum später gezielt anzugreifen."],
    mistakes: ["Zentrumsbesetzung wird mit Zentrumsbeherrschung gleichgesetzt und gegnerisches Gegenspiel ignoriert."],
    questions: ["Wer kontrolliert die zentralen Felder tatsächlich?", "Welcher Bauernhebel kann das gegnerische Zentrum herausfordern?"],
    training: "Markiere in Eröffnungsstellungen die zentralen Felder und notiere für beide Seiten Besetzung, Kontrolle und mögliche Bauernhebel.",
    related: ["pawns.pawn-break", "strategy.initiative", "opening.rapid-development"],
    signals: ["center-control-loss", "uncontested-pawn-center", "central-break-available"],
    keywords: ["zentrum", "zentrumsfelder", "bauernzentrum", "zentrumsbeherrschung"],
    phases: ["opening", "middlegame"],
  }),
  card({
    id: "opening.king-safety",
    en: "King Safety",
    de: "Königssicherheit",
    categories: ["opening", "evaluation", "defence", "king-attack"],
    definition: "Königssicherheit beschreibt, wie gut der König vor direkten Angriffen, offenen Linien und taktischen Schachs geschützt ist.",
    explanation: "Ein unsicherer König kann alle anderen Vorteile entwerten, weil forcierte Schachs die Entscheidungsfreiheit einschränken. Sicherheit hängt von Bauernschutz, offenen Linien, verfügbaren Verteidigern und Fluchtfeldern ab. Auch ein rochierter König ist nicht automatisch sicher.",
    cues: ["Der König steht im Zentrum, während Linien geöffnet werden können.", "Der Bauernschutz ist geschwächt oder wichtige Verteidiger fehlen."],
    recommendations: ["Bewerte vor aktiven Aktionen zuerst gegnerische Schachs und Linienöffnungen.", "Halte genügend Verteidiger und mindestens ein brauchbares Fluchtfeld bereit."],
    exceptions: ["Im Endspiel wird der König häufig zur aktiven Figur und soll zentralisiert werden."],
    mistakes: ["Rochade wird als vollständige Garantie für Sicherheit behandelt."],
    questions: ["Welche Schachs hat der Gegner sofort oder nach einer Linienöffnung?", "Welche Figur verteidigt die schwächsten Felder um meinen König?"],
    training: "Vergleiche in kritischen Stellungen Bauernschutz, offene Linien, Angreifer, Verteidiger und Fluchtfelder beider Könige.",
    related: ["opening.castling", "tactics.back-rank-tactic", "checkmate.mating-net"],
    signals: ["king-unsecured", "pawn-shield-weakened", "open-line-to-king"],
    keywords: ["königssicherheit", "offener könig", "bauernschild", "könig im zentrum"],
    phases: ["opening", "middlegame"],
  }),
  card({
    id: "opening.castling",
    en: "Castling",
    de: "Rochade",
    categories: ["opening", "defence"],
    definition: "Die Rochade bringt den König meist aus dem Zentrum und verbindet zugleich die Türme für das weitere Spiel.",
    explanation: "Rochieren löst zwei Entwicklungsaufgaben in einem Zug: Der König wird häufig sicherer und ein Turm wird aktiviert. Die richtige Seite und der richtige Zeitpunkt hängen jedoch von geöffneten Linien, Bauernschutz und gegnerischen Angriffsmöglichkeiten ab.",
    cues: ["Der König bleibt ohne konkreten Grund lange im offenen Zentrum.", "Die Rochade würde einen König direkt in einen bereits vorbereiteten Bauernsturm führen."],
    recommendations: ["Bereite die Rochade früh vor, ohne sie mechanisch auszuführen.", "Vergleiche vor der Seitenwahl Linien, Bauernschutz und gegnerische Angriffsrichtung."],
    exceptions: ["Bei geschlossenem Zentrum oder gefährlichem Flügel kann der König vorübergehend in der Mitte sicherer stehen."],
    mistakes: ["Automatische Rochade ohne Prüfung der gegnerischen Drohungen."],
    questions: ["Auf welcher Seite ist der König in den nächsten Zügen sicherer?", "Welche Linien werden durch die Rochade für meine Türme nutzbar?"],
    training: "Halte bei zehn eigenen Partien den Rochadezeitpunkt fest und bewerte anschließend, ob Sicherheit und Turmaktivität wirklich verbessert wurden.",
    related: ["opening.king-safety", "opening.rapid-development", "tactics.back-rank-tactic"],
    signals: ["king-on-starting-square-after-move-9", "castling-rights-retained"],
    keywords: ["rochade", "rochieren", "könig im zentrum", "türme verbinden"],
    phases: ["opening"],
  }),
  card({
    id: "tactics.fork",
    en: "Fork",
    de: "Gabel",
    categories: ["tactical-motifs", "pattern-recognition"],
    definition: "Eine Gabel ist ein Angriff, bei dem eine Figur gleichzeitig zwei oder mehr gegnerische Ziele bedroht.",
    explanation: "Weil der Gegner gewöhnlich nur eine Bedrohung pro Zug beantworten kann, gewinnt die angreifende Seite häufig Material. Springer- und Bauerngabeln sind besonders typisch, doch jede Figur kann eine Gabel erzeugen. Entscheidend sind Wert und Rettungsmöglichkeiten der Ziele.",
    cues: ["Zwei wertvolle gegnerische Figuren können von demselben Feld angegriffen werden.", "Ein Schachzug greift gleichzeitig eine zweite ungeschützte Figur an."],
    recommendations: ["Suche vor jedem Zug nach gemeinsamen Angriffsfeldern gegnerischer Figuren.", "Prüfe nach gegnerischen Zügen, ob zwei eigene wertvolle Ziele taktisch zusammenstehen."],
    exceptions: ["Eine scheinbare Gabel gewinnt nichts, wenn ein Ziel mit Tempo gerettet oder der Angreifer sofort geschlagen wird."],
    mistakes: ["Nur Springergabeln werden gesucht und Gegenangriffe auf den Gabelnden werden übersehen."],
    questions: ["Kann eine Figur zwei wertvollere Ziele gleichzeitig angreifen?", "Ist das Gabelungsfeld ausreichend geschützt?"],
    training: "Löse thematische Gabelaufgaben und benenne vor der Berechnung immer Angreifer, Ziele und das entscheidende Gabelungsfeld.",
    related: ["tactics.loose-piece", "calculation.checks-captures-threats", "tactics.deflection"],
    signals: ["fork-available", "double-attack", "fork-missed"],
    keywords: ["gabel", "doppelangriff", "springergabel", "zwei figuren angegriffen"],
    phases: ["all"],
  }),
  card({
    id: "tactics.pin",
    en: "Pin",
    de: "Fesselung",
    categories: ["tactical-motifs", "pattern-recognition"],
    definition: "Eine Fesselung hindert eine Figur am Ziehen, weil dahinter ein wertvolleres Ziel oder der eigene König steht.",
    explanation: "Bei einer absoluten Fesselung darf die Figur wegen des Königs nicht ziehen; bei einer relativen wäre der Zug legal, würde aber Material verlieren. Gefesselte Figuren können in ihrer Verteidigungswirkung eingeschränkt sein, bleiben jedoch nicht automatisch völlig wirkungslos.",
    cues: ["König, Dame oder Turm stehen auf derselben Linie hinter einer anderen Figur.", "Ein Linienangreifer kann durch Öffnen oder Besetzen dieser Linie Druck erzeugen."],
    recommendations: ["Prüfe bei Linienfiguren immer das Ziel hinter der vorderen Figur.", "Erhöhe den Druck auf eine gefesselte Figur nur, wenn sie sich nicht taktisch befreien kann."],
    exceptions: ["Eine relativ gefesselte Figur kann ziehen, wenn dadurch ein stärkerer taktischer Gewinn entsteht."],
    mistakes: ["Eine gefesselte Figur wird fälschlich als vollständig bewegungs- oder verteidigungsunfähig betrachtet."],
    questions: ["Was steht hinter der scheinbar gefesselten Figur?", "Kann die Fesselung durch Schach, Abtausch oder Zwischenzug gebrochen werden?"],
    training: "Ordne Fesselungsaufgaben nach absolut, relativ und scheinbar und berechne jeweils die beste Befreiungsmöglichkeit.",
    related: ["tactics.skewer", "tactics.removing-the-defender", "tactics.loose-piece"],
    signals: ["absolute-pin", "relative-pin", "pin-exploitable"],
    keywords: ["fesselung", "gefesselt", "absolute fesselung", "relative fesselung"],
    phases: ["all"],
  }),
  card({
    id: "tactics.skewer",
    en: "Skewer",
    de: "Spieß",
    categories: ["tactical-motifs", "pattern-recognition"],
    definition: "Ein Spieß greift ein wertvolles vorderes Ziel an und gewinnt nach dessen Ausweichen die dahinterstehende Figur.",
    explanation: "Der Spieß ähnelt einer umgekehrten Fesselung: Das wertvollere Ziel steht vorne und muss reagieren. Danach wird das weniger wertvolle Ziel auf derselben Linie erobert. Läufer, Türme und Damen nutzen dafür Reihen, Linien und Diagonalen.",
    cues: ["Zwei gegnerische Ziele stehen auf derselben Linie hintereinander.", "Das vordere Ziel ist so wertvoll oder bedroht, dass es ausweichen muss."],
    recommendations: ["Suche nach Linien, auf denen König oder Dame vor einer anderen Figur stehen.", "Prüfe vor der Ausführung, ob das hintere Ziel nach dem Ausweichen wirklich erreichbar bleibt."],
    exceptions: ["Der Spieß scheitert, wenn das vordere Ziel mit Gegenangriff ausweicht oder die Linie geschlossen werden kann."],
    mistakes: ["Fesselung und Spieß werden verwechselt, wodurch die Zugpflicht des vorderen Ziels falsch bewertet wird."],
    questions: ["Welches Ziel muss zuerst reagieren?", "Kann der Gegner nach dem Ausweichen das hintere Ziel zugleich schützen?"],
    training: "Löse Linienaufgaben und beschreibe vor jedem Zug die Reihenfolge vorderes Ziel, Ausweichen und Gewinn des hinteren Ziels.",
    related: ["tactics.pin", "tactics.deflection", "calculation.checks-captures-threats"],
    signals: ["skewer-available", "aligned-high-value-pieces"],
    keywords: ["spieß", "linie dahinter", "könig vor figur", "dame vor figur"],
    phases: ["all"],
  }),
  card({
    id: "tactics.discovered-attack",
    en: "Discovered Attack",
    de: "Abzugsangriff",
    categories: ["tactical-motifs", "pattern-recognition"],
    definition: "Beim Abzugsangriff zieht eine vordere Figur weg und öffnet dadurch den Angriff einer dahinterstehenden Linienfigur.",
    explanation: "Der abziehende Stein kann selbst eine zweite Drohung erzeugen, während Läufer, Turm oder Dame die geöffnete Linie nutzt. Besonders stark ist ein Abzugsschach, weil der Gegner auf das Schach reagieren muss und die zweite Drohung häufig bestehen bleibt.",
    cues: ["Eine eigene Figur steht vor einer Linienfigur auf derselben Reihe, Linie oder Diagonale.", "Das Wegziehen kann mit Schach, Angriff oder Materialgewinn verbunden werden."],
    recommendations: ["Prüfe bei jeder Batterie, welche aktiven Abzugsfelder die vordere Figur besitzt.", "Suche zuerst nach Abzügen mit Schach oder Angriff auf ein wertvolles Ziel."],
    exceptions: ["Das Öffnen der Linie ist nutzlos, wenn der hintere Angreifer selbst ungedeckt fällt oder das Ziel geschützt ist."],
    mistakes: ["Nur die geöffnete Linie wird betrachtet, nicht die Aufgabe und Sicherheit der abziehenden Figur."],
    questions: ["Welche Linie öffnet sich, wenn diese Figur zieht?", "Kann die abziehende Figur gleichzeitig eine zweite Drohung schaffen?"],
    training: "Trainiere Batteriestellungen und liste vor der Berechnung alle legalen Abzüge nach Schach, Schlagzug und Drohung.",
    related: ["tactics.fork", "tactics.deflection", "calculation.checks-captures-threats"],
    signals: ["discovered-attack", "discovered-check", "battery-aligned"],
    keywords: ["abzugsangriff", "abzugsschach", "linie öffnen", "batterie"],
    phases: ["all"],
  }),
  card({
    id: "tactics.deflection",
    en: "Deflection",
    de: "Ablenkung",
    categories: ["tactical-motifs", "pattern-recognition"],
    definition: "Eine Ablenkung zwingt eine gegnerische Figur, eine wichtige Verteidigungsaufgabe oder ein Schlüsselfeld aufzugeben.",
    explanation: "Verteidiger erfüllen oft mehrere Aufgaben: Sie schützen Material, decken Mattfelder oder kontrollieren Linien. Durch Opfer, Schachs oder Angriffe kann man sie von einer dieser Aufgaben weglocken. Die Folge muss konkret berechnet werden, weil die abgelenkte Figur neue Möglichkeiten erhalten kann.",
    cues: ["Eine einzelne Figur schützt ein entscheidendes Ziel oder Feld.", "Ein forcierter Angriff kann diesen Verteidiger auf ein anderes Feld zwingen."],
    recommendations: ["Frage bei jedem Verteidiger, was nach seinem Wegzug ungedeckt wäre.", "Berechne zuerst forcierte Ablenkungen durch Schach und Schlagzug."],
    exceptions: ["Eine Ablenkung funktioniert nicht, wenn ein zweiter Verteidiger übernehmen oder die Figur mit Gegentempo zurückkehren kann."],
    mistakes: ["Das gewünschte Wegziehen wird angenommen, ohne alternative Antworten des Gegners zu prüfen."],
    questions: ["Welche Aufgabe darf diese gegnerische Figur nicht aufgeben?", "Wie kann ich sie mit Tempo von dieser Aufgabe entfernen?"],
    training: "Löse Ablenkungsaufgaben und markiere jeweils Verteidiger, Pflichtaufgabe, Ablenkungszug und konkreten Gewinn.",
    related: ["tactics.removing-the-defender", "tactics.fork", "tactics.pin"],
    signals: ["deflection", "sole-defender", "defender-overloaded"],
    keywords: ["ablenkung", "verteidiger weglocken", "deckungsaufgabe", "überlastet"],
    phases: ["all"],
  }),
  card({
    id: "tactics.removing-the-defender",
    en: "Removing the Defender",
    de: "Beseitigung des Verteidigers",
    categories: ["tactical-motifs", "attack"],
    definition: "Die Beseitigung des Verteidigers entfernt eine Figur, die ein wichtiges Ziel, Feld oder eine Mattzone schützt.",
    explanation: "Viele Kombinationen werden erst möglich, wenn ein zentraler Verteidiger geschlagen, abgetauscht, gefesselt oder abgelenkt wird. Nicht jeder Verteidiger ist gleich wichtig: Entscheidend ist, ob nach seiner Entfernung ein konkreter Gewinn oder eine forcierte Drohung entsteht.",
    cues: ["Ein taktisches Ziel wird nur von einer entscheidenden Figur gehalten.", "Ein Abtausch oder Opfer kann diese Figur mit Tempo entfernen."],
    recommendations: ["Identifiziere vor einem Angriff den wichtigsten gegnerischen Verteidiger.", "Berechne nach seiner Entfernung auch gegnerische Zwischenzüge und Ersatzverteidiger."],
    exceptions: ["Der Abtausch ist falsch, wenn dadurch eine stärkere gegnerische Figur aktiviert oder kein konkreter Folgegewinn erreicht wird."],
    mistakes: ["Ein Verteidiger wird beseitigt, ohne die Stellung nach dem erzwungenen Rückschlag neu zu bewerten."],
    questions: ["Welche Figur hält die gegnerische Stellung zusammen?", "Was ist nach ihrem Abtausch tatsächlich ungedeckt oder unkontrolliert?"],
    training: "Wähle Kombinationen mit Verteidigerbeseitigung und benenne vor jeder Lösung Ziel, Schlüsselverteidiger und Folgegewinn.",
    related: ["tactics.deflection", "tactics.pin", "checkmate.mating-net"],
    signals: ["remove-defender", "sole-defender", "key-defender"],
    keywords: ["verteidiger beseitigen", "verteidiger entfernen", "schlüsselverteidiger", "deckungsfigur"],
    phases: ["all"],
  }),
  card({
    id: "tactics.zwischenzug",
    en: "Zwischenzug",
    de: "Zwischenzug",
    categories: ["tactical-motifs", "calculation"],
    definition: "Ein Zwischenzug unterbricht eine scheinbar erzwungene Zugfolge mit einer stärkeren unmittelbaren Drohung.",
    explanation: "Statt erwartungsgemäß zurückzuschlagen oder eine bedrohte Figur zu retten, spielt eine Seite zuerst einen zwingenderen Zug. Häufig handelt es sich um Schach, einen Angriff auf die Dame oder eine Mattdrohung. Danach kann sie zur ursprünglichen Aufgabe zurückkehren.",
    cues: ["Eine Abtauschfolge scheint automatisch, enthält aber eine kurze taktische Unterbrechung.", "Ein Schach oder Angriff mit höherer Dringlichkeit ist vor dem erwarteten Rückschlag möglich."],
    recommendations: ["Stoppe vor jedem automatischen Rückschlag und prüfe alle Schachs und starken Drohungen.", "Untersuche auch Zwischenzüge des Gegners in deiner geplanten Kombination."],
    exceptions: ["Der Zwischenzug ist nur gut, wenn die ursprüngliche Drohung danach weiterhin beherrscht oder übertroffen wird."],
    mistakes: ["Rückschläge werden mechanisch ausgeführt und die Zugreihenfolge nicht neu geprüft."],
    questions: ["Muss ich wirklich sofort zurückschlagen?", "Hat eine Seite zuerst ein Schach oder eine stärkere Drohung?"],
    training: "Nutze Aufgaben mit scheinbar erzwungenen Abtäuschen und suche vor jedem Rückschlag bewusst nach einem Zwischenzug.",
    related: ["calculation.checks-captures-threats", "calculation.blunder-check", "tactics.deflection"],
    signals: ["zwischenzug", "zwischencheck", "intermediate-move"],
    keywords: ["zwischenzug", "zwischencheck", "erst noch", "zugreihenfolge"],
    phases: ["all"],
  }),
  card({
    id: "tactics.loose-piece",
    en: "Loose Piece",
    de: "Ungedeckte oder lose Figur",
    categories: ["tactical-motifs", "tactical-preconditions", "mistake-classification"],
    definition: "Eine lose Figur ist ungedeckt oder unzureichend gedeckt und dadurch besonders anfällig für taktische Angriffe.",
    explanation: "Viele Taktiken funktionieren, weil nach einem forcierten Zug eine ungeschützte Figur übrig bleibt. Auch scheinbar gedeckte Figuren können lose sein, wenn ihr Verteidiger gefesselt, überlastet oder weniger wertvoll ist. Regelmäßige Figurenkontrolle verhindert einfache Materialverluste.",
    cues: ["Eine Figur besitzt keinen zuverlässigen Verteidiger.", "Einziger Verteidiger ist gefesselt, überlastet oder kann mit Tempo beseitigt werden."],
    recommendations: ["Führe nach jedem gegnerischen Zug einen kurzen Sicherheitscheck aller Figuren durch.", "Prüfe nicht nur die Anzahl, sondern auch die taktische Zuverlässigkeit der Verteidiger."],
    exceptions: ["Eine ungedeckte Figur kann sicher sein, wenn sie nicht erreichbar ist oder taktisch nicht genommen werden darf."],
    mistakes: ["Nur direkt angegriffene Figuren werden geprüft; lose Figuren als spätere taktische Ziele bleiben unbemerkt."],
    questions: ["Welche Figuren beider Seiten sind gerade ungedeckt?", "Kann ein Verteidiger durch einen forcierten Zug ausgeschaltet werden?"],
    training: "Halte in Taktikstellungen vor der Variantenberechnung alle ungedeckten und nur einmal gedeckten Figuren schriftlich fest.",
    related: ["tactics.fork", "tactics.pin", "calculation.blunder-check"],
    signals: ["loose-piece", "hanging-piece", "insufficiently-defended-piece"],
    keywords: ["lose figur", "ungedeckte figur", "hängt", "figur verloren"],
    phases: ["all"],
  }),
  card({
    id: "tactics.back-rank-tactic",
    en: "Back-Rank Tactic",
    de: "Grundreihentaktik",
    categories: ["tactical-motifs", "checkmate-patterns", "defence"],
    definition: "Eine Grundreihentaktik nutzt einen eingeschlossenen König, dem eigene Bauern oder Figuren die Fluchtfelder nehmen.",
    explanation: "Steht der König hinter seinem ungezogenen Bauernwall ohne Luftloch, können Schachs auf der Grundreihe zu Matt oder Materialgewinn führen. Selbst wenn kein unmittelbares Matt droht, sind Verteidiger oft an die Grundreihe gebunden und taktisch überlastet.",
    cues: ["Der König besitzt kein freies Fluchtfeld vor seiner Grundreihe.", "Gegnerische Türme oder die Dame können auf die Grundreihe eindringen."],
    recommendations: ["Prüfe rechtzeitig, ob ein Luftloch nötig und sicher ist.", "Nutze die Bindung gegnerischer Schwerfiguren an die Grundreihe für taktische Gewinne."],
    exceptions: ["Ein Luftloch kann selbst Felder schwächen; ohne konkrete Gefahr ist es nicht automatisch der beste Zug."],
    mistakes: ["Die Grundreihe wird erst geprüft, nachdem eine Schwerfigur bereits eingedrungen ist."],
    questions: ["Welches Fluchtfeld hat mein König nach einem Grundreihenschach?", "Welche meiner Figuren muss derzeit die Grundreihe bewachen?"],
    training: "Trainiere Grundreihenmotive paarweise aus Angreifer- und Verteidigersicht und entscheide, wann ein Luftloch wirklich nötig ist.",
    related: ["opening.king-safety", "checkmate.mating-net", "tactics.removing-the-defender"],
    signals: ["back-rank-weakness", "no-luft", "back-rank-tactic"],
    keywords: ["grundreihe", "luftloch", "grundreihenmatt", "eingesperrter könig"],
    phases: ["middlegame", "endgame"],
  }),
  card({
    id: "checkmate.mating-net",
    en: "Mating Net",
    de: "Mattnetz",
    categories: ["checkmate-patterns", "king-attack", "calculation"],
    difficulty: ["intermediate", "advanced"],
    definition: "Ein Mattnetz schränkt den König schrittweise so ein, dass mehrere Mattdrohungen nicht mehr vollständig pariert werden können.",
    explanation: "Ein Mattnetz besteht nicht zwingend aus einer sofortigen Schachserie. Häufig sind kontrollierte Fluchtfelder, abgeschnittene Verteidiger und ruhige Drohzüge wichtiger. Die Qualität des Netzes hängt davon ab, ob der Gegner alle Verteidigungsressourcen und Gegenchecks überlebt.",
    cues: ["Der König besitzt nur wenige Fluchtfelder und mehrere davon sind kontrolliert.", "Angreifer können mit Tempo weitere Figuren heranführen oder einen Schlüsselverteidiger entfernen."],
    recommendations: ["Kartiere Fluchtfelder und Verteidiger, bevor du Opfer berechnest.", "Prüfe gegnerische Gegenchecks, Abtäusche und Fluchtwege als beste Verteidigung."],
    exceptions: ["Ein optisch gefährlicher Angriff ist kein Mattnetz, wenn der Gegner durch Abtausch oder Flucht konsolidieren kann."],
    mistakes: ["Nur eigene Angriffszüge werden berechnet; aktive gegnerische Verteidigung bleibt unberücksichtigt."],
    questions: ["Welche Fluchtfelder bleiben dem König wirklich?", "Welcher gegnerische Verteidigungszug zerstört mein Netz am stärksten?"],
    training: "Analysiere Mattstellungen rückwärts: Bestimme zuerst das Endmuster und danach, wie Fluchtfelder und Verteidiger nacheinander ausgeschaltet wurden.",
    related: ["opening.king-safety", "tactics.removing-the-defender", "tactics.back-rank-tactic"],
    signals: ["mating-net", "restricted-king", "forced-mate-threat"],
    keywords: ["mattnetz", "mattangriff", "fluchtfelder", "könig gefangen"],
    phases: ["all"],
  }),
  card({
    id: "strategy.initiative",
    en: "Initiative",
    de: "Initiative",
    categories: ["strategy", "evaluation", "attack"],
    definition: "Initiative bedeutet, Drohungen zu stellen und dadurch die Antworten des Gegners über mehrere Züge zu bestimmen.",
    explanation: "Die Initiative ist dynamisch und kann schnell verschwinden. Sie kann Material oder strukturelle Nachteile vorübergehend kompensieren, wenn die Drohungen konkret genug sind. Wer die Initiative besitzt, muss häufig energisch handeln, ohne deshalb jede ruhige Verbesserung abzulehnen.",
    cues: ["Eine Seite stellt fortlaufend konkrete Drohungen mit Tempo.", "Der Gegner muss reagieren und kann seinen eigenen Plan kaum verfolgen."],
    recommendations: ["Suche nach Zügen, die Drohung, Entwicklung und Aktivität verbinden.", "Bewerte nach jeder Abwehr neu, ob die Initiative noch besteht oder konsolidiert werden muss."],
    exceptions: ["Scheinaktivität ohne konkrete Drohungen rechtfertigt keinen dauerhaften materiellen oder strukturellen Nachteil."],
    mistakes: ["Jeder aktive Zug wird als Initiative bezeichnet, obwohl der Gegner freie Wahl besitzt."],
    questions: ["Welche konkrete Antwort erzwingt mein Zug?", "Was bleibt von meinem Spiel übrig, wenn der Gegner die Drohung neutralisiert?"],
    training: "Markiere in Modellpartien jede Phase, in der eine Seite mehrere erzwungene Antworten erzeugt, und bestimme den Moment des Initiativewechsels.",
    related: ["opening.rapid-development", "opening.development-before-attack", "strategy.piece-coordination"],
    signals: ["initiative-gained", "forcing-sequence", "opponent-reacting"],
    keywords: ["initiative", "tempo", "druck", "gegner muss reagieren"],
    phases: ["opening", "middlegame"],
  }),
  card({
    id: "strategy.prophylaxis",
    en: "Prophylaxis",
    de: "Prophylaxe",
    categories: ["prophylaxis", "strategy", "decision-making", "defence"],
    definition: "Prophylaxe erkennt den gegnerischen Plan früh und erschwert oder verhindert ihn, bevor eine unmittelbare Drohung entsteht.",
    explanation: "Prophylaktisches Denken beginnt mit einem Perspektivwechsel: Was möchte der Gegner als Nächstes verbessern oder erzwingen? Eine gute vorbeugende Maßnahme neutralisiert diesen Plan möglichst ohne die eigene Stellung passiv zu machen und verbindet Abwehr mit eigener Verbesserung.",
    cues: ["Der Gegner besitzt einen klaren vorbereitenden Zug oder Bauernhebel.", "Ein ruhiger eigener Zug kann gegnerisches Gegenspiel dauerhaft einschränken."],
    recommendations: ["Formuliere vor deinem Zug den besten gegnerischen Plan in einem Satz.", "Bevorzuge vorbeugende Züge, die zugleich eine eigene Figur oder Struktur verbessern."],
    exceptions: ["Eine unmittelbare taktische Möglichkeit darf nicht zugunsten allgemeiner Vorbeugung verpasst werden."],
    mistakes: ["Prophylaxe wird mit passiver Verteidigung und dem Aufgeben eigener Pläne verwechselt."],
    questions: ["Was würde der Gegner bei einem freien Zug spielen?", "Kann ich diesen Plan verhindern und zugleich meine Stellung verbessern?"],
    training: "Halte in ruhigen Stellungen vor jedem Zug den gegnerischen Wunschzug fest und vergleiche ihn anschließend mit der Partiefortsetzung.",
    related: ["strategy.initiative", "strategy.improve-worst-piece", "calculation.blunder-check"],
    signals: ["opponent-plan", "counterplay-preventable", "prophylactic-move"],
    keywords: ["prophylaxe", "gegnerischer plan", "vorbeugen", "verhindern"],
    phases: ["middlegame", "endgame"],
  }),
  card({
    id: "strategy.weak-square",
    en: "Weak Square",
    de: "Schwaches Feld",
    categories: ["strategy", "positional-play", "evaluation"],
    definition: "Ein schwaches Feld kann von den eigenen Bauern nicht mehr zuverlässig kontrolliert und vom Gegner dauerhaft genutzt werden.",
    explanation: "Besonders wertvoll wird ein schwaches Feld, wenn eine gegnerische Figur dort sicher steht, wichtige Ziele angreift und schwer vertrieben werden kann. Nicht jedes unkontrollierte Feld ist relevant; Entfernung zum Geschehen, Zugänglichkeit und Nutzen eines Besetzers entscheiden.",
    cues: ["Eigene Bauern können ein Feld strukturell nicht mehr angreifen.", "Eine gegnerische Figur erreicht das Feld und erhält dort stabile Aufgaben oder Ziele."],
    recommendations: ["Bewerte schwache Felder nach Erreichbarkeit und Wirkung, nicht nur nach ihrer Farbe.", "Kontrolliere Zugangswege oder tausche die ideale gegnerische Besetzungsfigur ab."],
    exceptions: ["Ein formal schwaches Feld ist bedeutungslos, wenn keine gegnerische Figur es sinnvoll nutzen kann."],
    mistakes: ["Jedes Bauernloch wird automatisch als entscheidende Schwäche bewertet."],
    questions: ["Welche gegnerische Figur profitiert konkret von diesem Feld?", "Kann ich die Besetzung verhindern oder den Besetzer abtauschen?"],
    training: "Markiere in strategischen Stellungen Bauernlöcher und bewerte anschließend für jedes Feld Zugänglichkeit, Stabilität und konkrete Wirkung.",
    related: ["strategy.outpost", "strategy.piece-coordination", "pawns.isolated-pawn"],
    signals: ["weak-square", "pawn-hole", "square-exploitable"],
    keywords: ["schwaches feld", "bauernloch", "felderschwäche", "schwacher farbkomplex"],
    phases: ["middlegame", "endgame"],
  }),
  card({
    id: "strategy.outpost",
    en: "Outpost",
    de: "Vorposten",
    categories: ["strategy", "positional-play", "piece-activity"],
    definition: "Ein Vorposten ist ein stabiles vorgeschobenes Feld, auf dem eine Figur aktiv steht und nicht leicht von Bauern vertrieben wird.",
    explanation: "Springer profitieren besonders von zentralen Vorposten, weil ihre kurze Reichweite durch die stabile Position ausgeglichen wird. Ein Vorposten ist umso stärker, je besser er unterstützt ist, je mehr Ziele er beeinflusst und je weniger geeignete gegnerische Abtauschfiguren vorhanden sind.",
    cues: ["Ein vorgeschobenes Feld kann nicht mehr von gegnerischen Bauern angegriffen werden.", "Eine eigene Figur erreicht es, wird unterstützt und erzeugt konkrete Wirkung."],
    recommendations: ["Bereite den Zugang zum Vorposten vor und sichere den Besetzer ausreichend.", "Tausche gegnerische Figuren ab, die den Vorpostenbesetzer leicht beseitigen könnten."],
    exceptions: ["Ein stabiler Vorposten ist wertlos, wenn die Figur dort keine Ziele, Wege oder Verteidigungsaufgaben besitzt."],
    mistakes: ["Eine Figur wird nur wegen der optischen Zentralität auf einen Vorposten gestellt."],
    questions: ["Kann ein Bauer diese Figur künftig vertreiben?", "Welche konkreten Felder und Ziele kontrolliert die Figur vom Vorposten aus?"],
    training: "Suche in Modellpartien starke Springerfelder und begründe Stabilität, Unterstützung, Zugangsroute und Wirkung jedes Vorpostens.",
    related: ["strategy.weak-square", "strategy.piece-coordination", "strategy.improve-worst-piece"],
    signals: ["outpost-available", "protected-outpost", "knight-outpost"],
    keywords: ["vorposten", "springerfeld", "nicht vertreibbar", "starkes feld"],
    phases: ["middlegame", "endgame"],
  }),
  card({
    id: "strategy.improve-worst-piece",
    en: "Improving the Worst-Placed Piece",
    de: "Schlechteste Figur verbessern",
    categories: ["strategy", "planning", "piece-activity"],
    definition: "Das Prinzip verbessert zuerst die eigene Figur, die am wenigsten zum Spiel beiträgt oder den Plan behindert.",
    explanation: "In ruhigen Stellungen fehlen oft direkte Taktiken. Dann begrenzt die schlechteste Figur die Koordination der gesamten Armee. Eine Verbesserung kann Aktivierung, Umgruppierung, Befreiung von einer Verteidigungsaufgabe oder einen günstigen Abtausch bedeuten.",
    cues: ["Eine Figur besitzt kaum legale oder sinnvolle Felder und erfüllt keine aktive Aufgabe.", "Der eigene Plan scheitert daran, dass eine Figur nicht beteiligt oder im Weg ist."],
    recommendations: ["Vergleiche Aktivität und Aufgabe aller eigenen Figuren vor einem ruhigen Zug.", "Suche eine konkrete Route oder einen Abtausch, der die schlechteste Figur verbessert."],
    exceptions: ["Forcierte Taktik, unmittelbare Drohung oder notwendige Verteidigung hat Vorrang."],
    mistakes: ["Die optisch am weitesten hinten stehende Figur wird automatisch als schlechteste gewählt."],
    questions: ["Welche Figur trägt momentan am wenigsten bei?", "Auf welchem realistischen Weg kann sie eine sinnvolle Aufgabe übernehmen?"],
    training: "Pausiere Modellpartien in ruhigen Stellungen, wähle die schlechteste Figur und plane eine konkrete Umgruppierungsroute.",
    related: ["strategy.piece-coordination", "strategy.prophylaxis", "strategy.outpost"],
    signals: ["inactive-piece", "worst-placed-piece", "piece-improvement"],
    keywords: ["schlechteste figur", "figur verbessern", "passive figur", "umgruppieren"],
    phases: ["middlegame", "endgame"],
  }),
  card({
    id: "strategy.piece-coordination",
    en: "Piece Coordination",
    de: "Figurenkoordination",
    categories: ["strategy", "piece-activity", "evaluation"],
    definition: "Gute Figurenkoordination bedeutet, dass Figuren gemeinsame Ziele unterstützen, Felder decken und sich nicht gegenseitig behindern.",
    explanation: "Einzelne aktive Figuren reichen häufig nicht aus. Die Stärke einer Stellung entsteht aus dem Zusammenspiel: Angreifer konzentrieren sich auf dasselbe Ziel, Verteidiger entlasten einander und Linien bleiben frei. Koordination kann wichtiger sein als nominelles Material.",
    cues: ["Mehrere eigene Figuren wirken auf dasselbe relevante Ziel oder dieselbe Zone.", "Figuren blockieren einander, verteidigen doppelt unnötige Punkte oder verfolgen widersprüchliche Pläne."],
    recommendations: ["Bestimme für jede Figur eine konkrete Aufgabe im aktuellen Plan.", "Verbessere Verbindungen und gemeinsame Zielwirkung statt isolierte Aktivität."],
    exceptions: ["Eine taktisch dominante Einzelfigur kann vorübergehend wichtiger als harmonische Gesamtaufstellung sein."],
    mistakes: ["Aktivität wird nur anhand vorgeschobener Felder bewertet, ohne Zusammenarbeit und Sicherheit zu prüfen."],
    questions: ["Welche Figuren arbeiten derzeit am selben Ziel?", "Welche Figur steht einer anderen im Weg oder erfüllt keine passende Aufgabe?"],
    training: "Beschreibe in ausgewählten Stellungen die Aufgabe jeder Figur in einem Satz und suche anschließend Koordinationslücken.",
    related: ["strategy.improve-worst-piece", "strategy.initiative", "strategy.outpost"],
    signals: ["piece-coordination", "uncoordinated-pieces", "local-superiority"],
    keywords: ["koordination", "figuren zusammenspiel", "harmonie", "gemeinsames ziel"],
    phases: ["all"],
  }),
  card({
    id: "pawns.isolated-pawn",
    en: "Isolated Pawn",
    de: "Isolierter Bauer",
    categories: ["pawn-structures", "piece-evaluation", "planning"],
    definition: "Ein isolierter Bauer besitzt auf den benachbarten Linien keine eigenen Bauern und kann daher nicht von Bauern gedeckt werden.",
    explanation: "Der isolierte Bauer kann eine dauerhafte Schwäche sein, weil Figuren ihn verteidigen müssen und das Feld vor ihm blockiert werden kann. Gleichzeitig schafft er häufig offene Linien, Raum und aktive Figurenfelder. Seine Bewertung hängt stark von Aktivität und Endspielnähe ab.",
    cues: ["Auf beiden Nachbarlinien fehlt ein eigener Bauer.", "Der Bauer wird blockiert und bindet mehrere Figuren an seine Verteidigung."],
    recommendations: ["Nutze Aktivität und offene Linien, bevor vereinfachte Endspiele die Schwäche verstärken.", "Greife als Verteidiger zuerst das Blockadefeld und dann den isolierten Bauern an."],
    exceptions: ["Ein isolierter Bauer kann dynamische Vorteile bieten und ist nicht automatisch schlecht."],
    mistakes: ["Die Struktur wird statisch bewertet, ohne Raum, offene Linien und Angriffschancen einzubeziehen."],
    questions: ["Erzeugt der Bauer aktuell Aktivität oder nur Verteidigungspflichten?", "Welche Figur kann das Feld direkt vor dem Bauern blockieren?"],
    training: "Vergleiche Modellstellungen mit isoliertem Bauern im Mittelspiel und Endspiel und notiere jeweils dynamische sowie statische Faktoren.",
    related: ["pawns.pawn-break", "pawns.passed-pawn", "strategy.weak-square"],
    signals: ["isolated-pawn", "iqp", "blockade-square"],
    keywords: ["isolierter bauer", "isolani", "iqp", "bauernschwäche"],
    phases: ["middlegame", "endgame"],
  }),
  card({
    id: "pawns.passed-pawn",
    en: "Passed Pawn",
    de: "Freibauer",
    categories: ["pawn-structures", "pawn-play", "evaluation", "endgame-principles"],
    definition: "Ein Freibauer hat auf seiner und den benachbarten Linien keinen gegnerischen Bauern mehr vor sich, der ihn aufhalten kann.",
    explanation: "Seine Stärke wächst mit dem Vorrücken, weil er gegnerische Figuren zur Blockade bindet und die Umwandlung droht. Unterstützte, verbundene und entfernte Freibauern können besonders stark sein. Ein blockierter oder leicht angreifbarer Freibauer kann dagegen schwach bleiben.",
    cues: ["Kein gegnerischer Bauer kann den Bauern frontal oder von einer Nachbarlinie stoppen.", "Sein Vormarsch bindet gegnerische Figuren oder schafft eine konkrete Umwandlungsdrohung."],
    recommendations: ["Unterstütze den Vormarsch mit König und aktiven Figuren.", "Blockiere gegnerische Freibauern früh, bevor sie Raum und Tempi gewinnen."],
    exceptions: ["Ein weit vorgerückter Freibauer kann fallen, wenn seine Unterstützung fehlt oder der Gegner stärkere Drohungen besitzt."],
    mistakes: ["Freibauern werden blind vorgeschoben und dadurch von ihrer Unterstützung getrennt."],
    questions: ["Wie kann der Bauer sicher ein Feld weiterkommen?", "Welche gegnerische Figur ist an seine Blockade gebunden?"],
    training: "Übe Stellungen mit verschiedenen Freibauertypen und entscheide jeweils zwischen sofortigem Vormarsch, Unterstützung und Ablenkung.",
    related: ["endgame.opposition", "pawns.pawn-break", "pawns.isolated-pawn"],
    signals: ["passed-pawn", "protected-passed-pawn", "outside-passed-pawn"],
    keywords: ["freibauer", "gedeckter freibauer", "entfernter freibauer", "umwandlung"],
    phases: ["middlegame", "endgame"],
  }),
  card({
    id: "pawns.pawn-break",
    en: "Pawn Break",
    de: "Bauernhebel",
    categories: ["pawn-play", "pawn-structures", "planning", "transitions"],
    definition: "Ein Bauernhebel ist ein Bauernvorstoß, der gegnerische Bauern herausfordert und die bestehende Struktur gezielt verändert.",
    explanation: "Bauernhebel öffnen Linien, schaffen Freibauern, greifen Ketten an oder räumen Figurenfelder frei. Da Bauern nicht zurückziehen können, verändert ein Hebel die Stellung dauerhaft. Zeitpunkt, Vorbereitung und die entstehende Struktur sind wichtiger als bloßer Raumgewinn.",
    cues: ["Ein eigener Bauer kann einen gegnerischen Bauern direkt herausfordern.", "Die aktuelle Struktur begrenzt Figuren und kann durch einen vorbereiteten Vorstoß geöffnet werden."],
    recommendations: ["Berechne alle Schlagmöglichkeiten und die Struktur nach dem Tausch oder Vorbeiziehen.", "Bereite den Hebel mit besserer Figurenstellung und ausreichender Königssicherheit vor."],
    exceptions: ["Ein sofortiger Hebel kann taktisch nötig sein, bevor der Gegner konsolidiert oder selbst öffnet."],
    mistakes: ["Der Bauernzug wird gespielt, weil er verfügbar ist, ohne die irreversible Folgestruktur zu bewerten."],
    questions: ["Welche Linien und Felder entstehen nach jedem möglichen Bauernabtausch?", "Wessen Figuren profitieren stärker von der Öffnung?"],
    training: "Analysiere typische Bauernstrukturen und markiere für beide Seiten den wichtigsten Hebel, seine Vorbereitung und den besten Zeitpunkt.",
    related: ["opening.fight-for-centre", "pawns.passed-pawn", "pawns.isolated-pawn"],
    signals: ["pawn-break", "central-break-available", "structure-transformable"],
    keywords: ["bauernhebel", "bauernbruch", "struktur öffnen", "zentrum sprengen"],
    phases: ["opening", "middlegame", "endgame"],
  }),
  card({
    id: "calculation.candidate-move-generation",
    en: "Candidate-Move Generation",
    de: "Kandidatenzüge bilden",
    categories: ["calculation", "decision-making", "training-methods"],
    definition: "Kandidatenzüge sind eine kleine, begründete Auswahl ernsthafter Möglichkeiten, die vor der tiefen Berechnung verglichen werden.",
    explanation: "Wer sofort den ersten attraktiven Zug berechnet, übersieht oft stärkere Alternativen. Eine gute Kandidatenliste enthält forcierte Züge, natürliche Verbesserungen und gegnerbezogene Maßnahmen. Sie bleibt klein genug, damit jede Möglichkeit diszipliniert geprüft werden kann.",
    cues: ["Die Stellung bietet mehrere plausible Pläne oder taktische Möglichkeiten.", "Die Berechnung springt ungeordnet zwischen vielen Zügen oder bleibt am ersten Einfall hängen."],
    recommendations: ["Sammle vor tiefer Berechnung zwei bis vier ernsthafte Züge.", "Begründe jeden Kandidaten durch Drohung, Verbesserung, Verteidigung oder Stellungsanforderung."],
    exceptions: ["Bei einem eindeutig erzwungenen Zug ist eine breite Kandidatensuche unnötig, doch die Erzwingung muss geprüft werden."],
    mistakes: ["Nur Schachs und Schlagzüge werden aufgenommen; starke ruhige Züge fehlen."],
    questions: ["Welche forcierte Möglichkeit darf ich nicht übersehen?", "Welcher ruhige Zug erfüllt die wichtigste Stellungsanforderung?"],
    training: "Bearbeite Stellungen ohne sofort zu ziehen: Notiere drei Kandidaten samt Begründung und berechne erst danach jeden einzeln.",
    related: ["calculation.checks-captures-threats", "calculation.blunder-check", "strategy.prophylaxis"],
    signals: ["candidate-moves-needed", "first-move-bias", "multiple-plans"],
    keywords: ["kandidatenzüge", "welche züge prüfen", "zugauswahl", "erster einfall"],
    phases: ["all"],
  }),
  card({
    id: "calculation.checks-captures-threats",
    en: "Checks, Captures, and Threats",
    de: "Schachs, Schlagzüge und Drohungen",
    categories: ["calculation", "tactical-motifs", "decision-making"],
    definition: "Schachs, Schlagzüge und konkrete Drohungen bilden eine Suchordnung für forcierte Kandidaten und gegnerische Antworten.",
    explanation: "Forcierte Züge begrenzen die Antwortmöglichkeiten und sind deshalb in taktischen Stellungen besonders wichtig. Die Reihenfolge ist eine Suchhilfe, kein Gesetz: Ein sinnloses Schach bleibt schlecht, und ein ruhiger Zug kann stärker sein. Jede Möglichkeit braucht eine konkrete Folgeprüfung.",
    cues: ["Die Stellung enthält exponierte Könige, angegriffene Figuren oder unmittelbare Drohungen.", "Ein kritischer Moment verlangt präzise Berechnung statt allgemeiner Planung."],
    recommendations: ["Prüfe forcierte Möglichkeiten für beide Seiten, nicht nur die eigenen.", "Verwirf oberflächliche Schachs, sobald sie dem Gegner helfen oder nichts erreichen."],
    exceptions: ["In ruhigen Stellungen kann die wichtigste Lösung eine prophylaktische oder positionelle Verbesserung sein."],
    mistakes: ["Die Merkhilfe wird mechanisch angewendet und erzeugt bedeutungslose Schachzüge."],
    questions: ["Welche Schachs und Schlagzüge verändern die Stellung wirklich?", "Welche stärkste Drohung besitzt der Gegner nach meinem Kandidaten?"],
    training: "Löse taktische Aufgaben, indem du vor der Berechnung für beide Seiten Schachs, Schlagzüge und ernsthafte Drohungen auflistest.",
    related: ["calculation.candidate-move-generation", "calculation.blunder-check", "tactics.zwischenzug"],
    signals: ["forcing-moves", "checks-captures-threats", "tactical-position"],
    keywords: ["schachs schlagzüge drohungen", "forcierte züge", "forcing moves", "taktisch rechnen"],
    phases: ["all"],
  }),
  card({
    id: "calculation.blunder-check",
    en: "Blunder Check",
    de: "Patzerkontrolle",
    categories: ["calculation", "decision-making", "mistake-classification", "practical-chess"],
    definition: "Die Patzerkontrolle ist eine kurze letzte Prüfung des geplanten Zuges auf gegnerische Schachs, Schlagzüge und direkte Drohungen.",
    explanation: "Viele Fehler entstehen nicht durch fehlendes Wissen, sondern durch einen ausgelassenen Abschlusscheck. Nach der Entscheidung sollte die neue Stellung im Kopf betrachtet werden: Was ist jetzt ungedeckt, welche Linie wurde geöffnet und welche forcierte Antwort besitzt der Gegner?",
    cues: ["Ein Zug wirkt selbstverständlich oder wird unter Zeitdruck automatisch gespielt.", "Der geplante Zug verändert Deckungen, Linien oder die Sicherheit des Königs."],
    recommendations: ["Setze den geplanten Zug gedanklich aufs Brett und suche die stärkste gegnerische Antwort.", "Prüfe besonders Schachs, Schlagzüge, Drohungen und neu ungedeckte Figuren."],
    exceptions: ["Bei extremer Zeitnot muss der Check verkürzt, aber nicht vollständig ausgelassen werden."],
    mistakes: ["Die bisherige Berechnung wird nur bestätigt, statt aktiv nach einer Widerlegung zu suchen."],
    questions: ["Was ist die stärkste forcierte Antwort des Gegners?", "Welche eigene Figur oder welches Feld ist nach meinem Zug neu ungeschützt?"],
    training: "Nutze in Trainingspartien vor jedem ausgeführten Zug eine feste kurze Routine: neue Stellung, gegnerisches Schach, Schlagzug, Drohung.",
    related: ["tactics.loose-piece", "calculation.checks-captures-threats", "calculation.candidate-move-generation"],
    signals: ["engine-classified-error", "engine-classified-blunder"],
    keywords: ["patzerkontrolle", "blunder check", "letzte prüfung", "gegnerische antwort"],
    phases: ["all"],
  }),
  card({
    id: "endgame.opposition",
    en: "Opposition",
    de: "Opposition",
    categories: ["pawn-endgames", "endgame-principles", "pattern-recognition"],
    definition: "Opposition ist eine Königskonstellation, bei der ein Zugzwang den gegnerischen König zum Zurückweichen oder Ausweichen zwingt.",
    explanation: "In Bauernendspielen entscheidet die Opposition häufig über Zugang zu Schlüsselfeldern. Direkte, entfernte und diagonale Opposition sind Formen desselben Prinzips: Der richtige Abstand und die Zugpflicht bestimmen, welcher König eindringen oder den gegnerischen König abdrängen kann.",
    cues: ["Die Könige stehen mit einem Feld Abstand auf derselben Linie oder können eine entsprechende Zugzwangstellung erreichen.", "Der Zugang zu einem Schlüsselfeld hängt davon ab, welcher König zuerst ausweichen muss."],
    recommendations: ["Bestimme zuerst Schlüsselfelder und gewünschte Eindringroute, nicht nur die geometrische Opposition.", "Nutze Reservetempi von Bauern, um die Zugpflicht günstig zu verändern."],
    exceptions: ["Opposition allein gewinnt nicht, wenn keine relevanten Schlüsselfelder oder Bauernziele erreichbar sind."],
    mistakes: ["Die Könige werden geometrisch gegenübergestellt, ohne Zugrecht und konkretes Ziel zu berücksichtigen."],
    questions: ["Welches Schlüsselfeld möchte mein König erreichen?", "Wer muss in der entscheidenden Königsstellung ziehen?"],
    training: "Spiele elementare König-und-Bauer-Stellungen von beiden Seiten aus und erkläre bei jedem Königszug Schlüsselfeld, Zugpflicht und Opposition.",
    related: ["pawns.passed-pawn", "strategy.prophylaxis", "calculation.blunder-check"],
    signals: ["opposition", "key-squares", "king-pawn-endgame"],
    keywords: ["opposition", "könige gegenüber", "schlüsselfelder", "bauernendspiel"],
    phases: ["endgame"],
  }),
]);
